@php
    $brandName = \App\Models\PlatformSetting::valueFor('brand_name', config('branding.name'));
    $productName = \App\Models\PlatformSetting::valueFor('product_name', config('branding.product_name'));
    $childSafetyEmail = 'muyiwah457@gmail.com';
@endphp
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="description" content="{{ $productName }} standards against child sexual abuse and exploitation.">
    <title>Child Safety Standards · {{ $productName }}</title>
    <style>
        :root{--navy:#0b1f3a;--red:#e4002b;--red-dark:#b90022;--red-soft:#fff0f3;--ink:#101828;--muted:#667085;--line:#e8e9ed;--white:#fff;--soft:#f7f9fb}
        *{box-sizing:border-box}html{scroll-behavior:smooth}body{margin:0;color:var(--ink);font-family:Inter,ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;background:var(--soft)}a{color:var(--red-dark)}.wrap{width:min(1040px,calc(100% - 40px));margin:auto}.nav{height:88px;display:flex;align-items:center;justify-content:space-between;gap:20px}.brand img{width:178px;height:62px;object-fit:contain;object-position:left center}.back{text-decoration:none;color:var(--navy);font-size:14px;font-weight:750}.hero{background:linear-gradient(145deg,#fff 0%,#fff8f9 100%);border-block:1px solid var(--line);padding:66px 0}.eyebrow{color:var(--red);font-size:12px;font-weight:850;letter-spacing:.1em;text-transform:uppercase}.hero h1{max-width:850px;font-size:clamp(38px,6vw,62px);line-height:1.05;letter-spacing:-.05em;color:var(--navy);margin:13px 0 15px}.hero p{max-width:760px;color:var(--muted);font-size:16px;line-height:1.7;margin:0}.updated{display:inline-block;margin-top:19px;padding:8px 12px;border-radius:999px;background:var(--red-soft);color:var(--red-dark);font-size:12px;font-weight:750}.layout{display:grid;grid-template-columns:230px minmax(0,1fr);gap:42px;padding:52px 0 80px}.toc{position:sticky;top:24px;align-self:start;background:var(--white);border:1px solid var(--line);border-radius:18px;padding:18px}.toc strong{display:block;color:var(--navy);font-size:13px;margin-bottom:10px}.toc a{display:block;text-decoration:none;color:var(--muted);font-size:12px;line-height:1.45;padding:7px 0}.document{background:var(--white);border:1px solid var(--line);border-radius:24px;padding:clamp(24px,5vw,52px)}.notice{padding:16px 18px;border-left:3px solid var(--red);background:var(--red-soft);border-radius:0 13px 13px 0;color:#5f2632;font-size:13px;line-height:1.65;margin-bottom:34px}.document section{scroll-margin-top:24px;margin-top:38px}.document section:first-of-type{margin-top:0}.document h2{color:var(--navy);font-size:23px;letter-spacing:-.02em;margin:0 0 13px}.document p,.document li{color:#475467;font-size:14px;line-height:1.8}.document p{margin:9px 0}.document ul{padding-left:21px;margin:9px 0}.document li+li{margin-top:7px}.contact{margin-top:18px;padding:20px;border-radius:16px;background:var(--soft);border:1px solid var(--line)}footer{padding:30px 0;border-top:1px solid var(--line);background:var(--white)}.footer{display:flex;justify-content:space-between;gap:20px;color:var(--muted);font-size:13px}.footer a{text-decoration:none;font-weight:700}@media(max-width:760px){.wrap{width:min(100% - 28px,1040px)}.layout{grid-template-columns:1fr;padding-top:26px}.toc{position:static}.document{border-radius:18px}.footer{flex-direction:column}.hero{padding:48px 0}}
    </style>
</head>
<body>
<header class="wrap nav"><a class="brand" href="{{ url('/') }}"><img src="{{ asset('images/brand-logo.png') }}" alt="{{ $brandName }}"></a><a class="back" href="{{ url('/') }}">← Back to home</a></header>
<main>
    <div class="hero"><div class="wrap"><span class="eyebrow">Trust and safety</span><h1>Child Safety Standards Against Child Sexual Abuse and Exploitation</h1><p>{{ $productName }} is committed to providing a safe environment for all users and maintaining a zero-tolerance approach to child sexual abuse and exploitation (CSAE) and child sexual abuse material (CSAM).</p><span class="updated">Last updated August 17, 2026</span></div></div>
    <div class="wrap layout">
        <aside class="toc"><strong>On this page</strong><a href="#zero-tolerance">1. Zero-tolerance policy</a><a href="#reporting">2. Reporting concerns</a><a href="#enforcement">3. Review and enforcement</a><a href="#csam">4. CSAM</a><a href="#protection">5. Grooming and exploitation</a><a href="#authorities">6. Cooperation with authorities</a><a href="#responsibility">7. User responsibility</a><a href="#changes">8. Changes</a><a href="#contact">9. Child safety contact</a></aside>
        <article class="document">
            <div class="notice">These standards explain our approach to preventing, identifying, reporting and responding to content or conduct that may involve the sexual abuse or exploitation of children.</div>
            <section id="zero-tolerance"><h2>1. Zero-Tolerance Policy</h2><p>{{ $productName }} strictly prohibits any content, activity, communication or behavior that sexually exploits, abuses, endangers or facilitates harm to children.</p><p>Prohibited activities include, but are not limited to:</p><ul><li>Creating, uploading, sharing, distributing, requesting or promoting child sexual abuse material (CSAM).</li><li>Sexual exploitation or abuse of minors.</li><li>Grooming or attempting to establish contact with a minor for sexual purposes.</li><li>Sexual solicitation involving minors.</li><li>Sextortion or blackmail involving minors.</li><li>Trafficking or facilitating the exploitation of children.</li><li>Sharing links or directing users to external locations containing CSAM.</li><li>Encouraging, normalizing, promoting or facilitating child sexual abuse or exploitation.</li><li>Using {{ $productName }} to arrange inappropriate or exploitative interactions with minors.</li></ul><p>Content or accounts that violate these standards may be removed or restricted, and responsible users may have their access suspended or permanently terminated.</p></section>
            <section id="reporting"><h2>2. Reporting Child Safety Concerns</h2><p>Users should immediately report content, accounts, messages or other activity that they reasonably believe may involve child sexual abuse, exploitation, grooming or other threats to the safety of children.</p><p>Where in-app reporting is available, use the relevant <strong>Report</strong> option associated with the content, account or interaction. Concerns may also be reported directly to our designated safety contact at <a href="mailto:{{ $childSafetyEmail }}">{{ $childSafetyEmail }}</a>.</p><p>Reports involving the immediate safety of a child should also be reported to the appropriate local law-enforcement or emergency authority.</p></section>
            <section id="enforcement"><h2>3. Review and Enforcement</h2><p>Reports involving suspected CSAE or CSAM are treated seriously and should receive priority review. Where a violation is identified, {{ $productName }} may:</p><ul><li>Remove prohibited content.</li><li>Restrict access to content or features.</li><li>Suspend or permanently disable offending accounts.</li><li>Preserve relevant information where required by applicable law.</li><li>Cooperate with lawful investigations.</li><li>Report suspected child sexual exploitation or abuse to appropriate authorities where legally required.</li></ul><p>Attempts to evade enforcement actions by creating new accounts or otherwise circumventing safety measures are not tolerated.</p></section>
            <section id="csam"><h2>4. CSAM</h2><p>Child sexual abuse material is strictly prohibited on {{ $productName }}. Users must never upload, distribute, request, possess, promote or facilitate access to CSAM through the platform.</p><p>Where suspected CSAM is identified, we will take appropriate action in accordance with applicable laws and reporting requirements. This may include restricting access, preserving relevant information as legally required, terminating accounts and reporting suspected illegal material to the appropriate regional or national authorities.</p></section>
            <section id="protection"><h2>5. Protecting Children From Grooming and Exploitation</h2><p>{{ $productName }} prohibits using the platform to groom, manipulate, solicit, coerce, threaten or sexually exploit children.</p><p>We may take action against accounts or content demonstrating behavior reasonably associated with child exploitation, including attempts to move inappropriate conversations with minors to other platforms or communication channels.</p></section>
            <section id="authorities"><h2>6. Cooperation With Authorities</h2><p>{{ $productName }} complies with applicable child-safety laws and responds to valid legal requests from authorized law-enforcement and regulatory authorities.</p><p>Where required by applicable law, confirmed or suspected instances of child sexual abuse, exploitation or CSAM may be reported to the appropriate regional, national or other legally designated authorities.</p></section>
            <section id="responsibility"><h2>7. User Responsibility</h2><p>All users are expected to comply with these Child Safety Standards, our Terms of Service, Community Guidelines and applicable laws.</p><p>Users should not independently redistribute suspected CSAM for the purpose of reporting it. Instead, they should use the available reporting mechanisms and provide sufficient information for the concern to be investigated.</p></section>
            <section id="changes"><h2>8. Changes to These Standards</h2><p>{{ $productName }} may periodically update these Child Safety Standards to reflect changes to our services, safety practices, legal obligations or regulatory requirements. The most recent version will be made publicly available on this page.</p></section>
            <section id="contact"><h2>9. Child Safety Contact</h2><p>Questions or reports concerning {{ $productName }}'s child-safety practices, CSAE prevention or CSAM compliance may be directed to:</p><div class="contact"><p><strong>{{ $productName }} – Child Safety Contact</strong><br>Email: <a href="mailto:{{ $childSafetyEmail }}">{{ $childSafetyEmail }}</a></p></div><p>{{ $productName }} remains committed to maintaining a platform that does not tolerate child sexual abuse, exploitation or content that endangers children.</p></section>
        </article>
    </div>
</main>
<footer><div class="wrap footer"><span>© {{ date('Y') }} {{ $brandName }}.</span><span><a href="{{ route('privacy') }}">Privacy Policy</a> · <a href="{{ route('terms') }}">Terms &amp; Conditions</a> · <a href="{{ route('account-deletion') }}">Delete Account</a></span></div></footer>
</body>
</html>
