@php
    $brandName = \App\Models\PlatformSetting::valueFor('brand_name', config('branding.name'));
    $productName = \App\Models\PlatformSetting::valueFor('product_name', config('branding.product_name'));
    $supportEmail = \App\Models\PlatformSetting::valueFor('support_email', config('branding.support_email'));
    $isPrivacy = $document === 'privacy';
    $title = $isPrivacy ? 'Privacy Policy' : 'Terms and Conditions';
    $effectiveDate = '14 August 2026';
@endphp
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="description" content="{{ $title }} for {{ $productName }}.">
    <title>{{ $title }} · {{ $productName }}</title>
    <style>
        :root{--navy:#0b1f3a;--red:#e4002b;--red-dark:#b90022;--red-soft:#fff0f3;--ink:#101828;--muted:#667085;--line:#e8e9ed;--white:#fff;--soft:#f7f9fb}
        *{box-sizing:border-box}html{scroll-behavior:smooth}body{margin:0;color:var(--ink);font-family:Inter,ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;background:var(--soft)}a{color:var(--red-dark)}.wrap{width:min(1040px,calc(100% - 40px));margin:auto}.nav{height:88px;display:flex;align-items:center;justify-content:space-between;gap:20px}.brand img{width:178px;height:62px;object-fit:contain;object-position:left center}.back{text-decoration:none;color:var(--navy);font-size:14px;font-weight:750}.hero{background:linear-gradient(145deg,#fff 0%,#fff8f9 100%);border-block:1px solid var(--line);padding:66px 0}.eyebrow{color:var(--red);font-size:12px;font-weight:850;letter-spacing:.1em;text-transform:uppercase}.hero h1{font-size:clamp(40px,6vw,64px);line-height:1.04;letter-spacing:-.05em;color:var(--navy);margin:13px 0 15px}.hero p{max-width:700px;color:var(--muted);font-size:16px;line-height:1.7;margin:0}.updated{display:inline-block;margin-top:19px;padding:8px 12px;border-radius:999px;background:var(--red-soft);color:var(--red-dark);font-size:12px;font-weight:750}.layout{display:grid;grid-template-columns:230px minmax(0,1fr);gap:42px;padding:52px 0 80px}.toc{position:sticky;top:24px;align-self:start;background:var(--white);border:1px solid var(--line);border-radius:18px;padding:18px}.toc strong{display:block;color:var(--navy);font-size:13px;margin-bottom:10px}.toc a{display:block;text-decoration:none;color:var(--muted);font-size:12px;line-height:1.45;padding:7px 0}.toc a:hover{color:var(--red)}.document{background:var(--white);border:1px solid var(--line);border-radius:24px;padding:clamp(24px,5vw,52px)}.notice{padding:16px 18px;border-left:3px solid var(--red);background:var(--red-soft);border-radius:0 13px 13px 0;color:#5f2632;font-size:13px;line-height:1.65;margin-bottom:34px}.document section{scroll-margin-top:24px;margin-top:38px}.document section:first-of-type{margin-top:0}.document h2{color:var(--navy);font-size:23px;letter-spacing:-.02em;margin:0 0 13px}.document h3{color:var(--navy);font-size:16px;margin:22px 0 8px}.document p,.document li{color:#475467;font-size:14px;line-height:1.8}.document p{margin:9px 0}.document ul{padding-left:21px;margin:9px 0}.document li+li{margin-top:7px}.contact{margin-top:40px;padding:20px;border-radius:16px;background:var(--soft);border:1px solid var(--line)}footer{padding:30px 0;border-top:1px solid var(--line);background:var(--white)}.footer{display:flex;justify-content:space-between;gap:20px;color:var(--muted);font-size:13px}.footer a{text-decoration:none;font-weight:700}
        @media(max-width:760px){.wrap{width:min(100% - 28px,1040px)}.layout{grid-template-columns:1fr;padding-top:26px}.toc{position:static}.document{border-radius:18px}.footer{flex-direction:column}.hero{padding:48px 0}}
    </style>
</head>
<body>
<header class="wrap nav"><a class="brand" href="{{ url('/') }}"><img src="{{ asset('images/brand-logo.png') }}" alt="{{ $brandName }}"></a><a class="back" href="{{ url('/') }}">← Back to home</a></header>
<main>
    <div class="hero"><div class="wrap"><span class="eyebrow">{{ $productName }} legal</span><h1>{{ $title }}</h1><p>{{ $isPrivacy ? 'How we collect, use, protect and manage information when you use our faith-centred social platform.' : 'The rules that help keep our faith-centred social platform safe, respectful and useful for everyone.' }}</p><span class="updated">Effective {{ $effectiveDate }}</span></div></div>
    <div class="wrap layout">
        <aside class="toc"><strong>On this page</strong>
            @if($isPrivacy)
                <a href="#scope">1. Scope</a><a href="#collect">2. Information we collect</a><a href="#use">3. How we use information</a><a href="#sharing">4. Sharing and visibility</a><a href="#storage">5. Storage and security</a><a href="#retention">6. Retention and deletion</a><a href="#choices">7. Your choices</a><a href="#children">8. Children</a><a href="#changes">9. Changes</a><a href="#contact">10. Contact</a>
            @else
                <a href="#agreement">1. Agreement</a><a href="#account">2. Accounts</a><a href="#conduct">3. Community conduct</a><a href="#content">4. Your content</a><a href="#moderation">5. Moderation</a><a href="#privacy">6. Privacy and safety</a><a href="#service">7. The service</a><a href="#termination">8. Suspension and termination</a><a href="#liability">9. Disclaimers</a><a href="#changes">10. Changes and contact</a>
            @endif
        </aside>
        <article class="document">
        @if($isPrivacy)
            <div class="notice">This policy describes {{ $productName }} as currently implemented. App-store disclosures and operational practices should remain consistent with this document.</div>
            <section id="scope"><h2>1. Scope and who we are</h2><p>{{ $productName }} is a social platform operated by {{ $brandName }} (“we”, “us” or “our”). This Privacy Policy applies to our mobile application, website, communities, support services and related features.</p><p>By using {{ $productName }}, you acknowledge the practices described here. Please contact us before using the service if you have questions about your information.</p></section>
            <section id="collect"><h2>2. Information we collect</h2><h3>Information you provide</h3><ul><li><strong>Account details:</strong> name, email address, password credentials and email-verification information.</li><li><strong>Profile details:</strong> profile photo, biography, phone number, date of birth, marital status, occupation, workplace, hobbies and privacy preferences when you choose to provide them.</li><li><strong>Content and communications:</strong> posts, photographs, comments, replies, reposts, reactions, saved-post activity and private messages or voice notes.</li><li><strong>Community information:</strong> memberships, applications, eligibility responses, commitments, quiz activity and content submitted for moderation.</li><li><strong>Support information:</strong> feedback, support requests and related correspondence.</li></ul><h3>Information collected through use</h3><ul><li>Friendships, blocks, community participation, notification status and other interactions needed to operate your account.</li><li>Device platform, push-notification token and device name or model when you enable push notifications.</li><li>Technical records such as IP address, request timestamps, error and security logs that our hosting infrastructure may process to deliver and protect the service.</li></ul><p>We do not intentionally request access to your contacts. Camera, photo-library or microphone access is used only when you choose features that require it, such as uploading an image or recording a voice note.</p></section>
            <section id="use"><h2>3. How we use information</h2><ul><li>Create and secure accounts, verify email addresses and provide password recovery.</li><li>Display profiles and content according to your settings and relationships.</li><li>Provide feeds, communities, friendships, private chats, moderation, quizzes, saved posts and notifications.</li><li>Review community applications, enforce our Terms and investigate abuse, fraud or security incidents.</li><li>Respond to support requests and maintain, diagnose and improve service reliability.</li><li>Comply with lawful requests and protect the rights, safety and integrity of members, the public and the platform.</li></ul><p>We do not sell personal information or use member information for third-party behavioural advertising.</p></section>
            <section id="sharing"><h2>4. Sharing and visibility</h2><p>Your display name, profile photo, biography, public posts and community activity may be visible to other members. Private-profile settings limit specified profile details, but do not make all account activity anonymous. Content shared in a community is visible to the people permitted to access that community.</p><p>Private messages are available to their participants and may be accessed by authorised personnel only where reasonably necessary for support, safety, legal compliance or enforcement. Community applications and moderated submissions are available to authorised reviewers.</p><p>We may use hosting, email delivery, media storage and push-notification providers to process information on our behalf. These providers receive only the information needed to perform their services. We may also disclose information when required by law, to protect safety or rights, during a business reorganisation with appropriate safeguards, or when you direct us to do so.</p></section>
            <section id="storage"><h2>5. Storage and security</h2><p>We use reasonable administrative, technical and organisational safeguards designed to protect information, including access controls, password hashing and authenticated application requests. No internet service can guarantee absolute security. Keep your password confidential and contact us if you suspect unauthorised account access.</p><p>Our service providers may process information in countries other than your own. Where required, we take appropriate steps to protect information transferred across borders.</p></section>
            <section id="retention"><h2>6. Retention and deletion</h2><p>We retain information while your account is active and for as long as reasonably needed to provide the service, maintain security, resolve disputes, enforce agreements and meet legal obligations. Retention periods vary by the type and purpose of the information.</p><p>You can delete your account from the app. Account deletion removes or de-identifies account data and content from active systems, subject to reasonable backup cycles and information we must retain for legal, fraud-prevention or safety reasons. Content previously shared or copied by others may remain outside our control.</p></section>
            <section id="choices"><h2>7. Your choices and rights</h2><ul><li>Edit your account and optional profile information in the app.</li><li>Use profile privacy controls and manage friendships or blocked accounts.</li><li>Control push notifications through your device settings.</li><li>Delete posts where the app provides that control and delete your account through Profile settings.</li><li>Contact us to request access, correction, deletion or other rights available under applicable law.</li></ul><p>We may need to verify your identity before completing a privacy request.</p></section>
            <section id="children"><h2>8. Children</h2><p>{{ $productName }} is not directed to children under 13, or any higher minimum age required to consent to data processing where they live. We do not knowingly collect personal information from children below the applicable minimum age. Contact us if you believe a child has provided such information.</p></section>
            <section id="changes"><h2>9. Changes to this policy</h2><p>We may update this policy as the service or legal requirements change. We will post the revised policy here, update the effective date and provide additional notice when a change is material.</p></section>
            <section id="contact"><h2>10. Contact us</h2><div class="contact"><p><strong>{{ $brandName }}</strong><br>Privacy inquiries and requests: <a href="mailto:{{ $supportEmail }}">{{ $supportEmail }}</a></p></div></section>
        @else
            <div class="notice">These Terms govern use of {{ $productName }}. They include rules for user-generated content, moderation and account enforcement.</div>
            <section id="agreement"><h2>1. Agreement to these Terms</h2><p>These Terms and Conditions (“Terms”) are an agreement between you and {{ $brandName }} governing your use of {{ $productName }}. By creating an account or using the service, you agree to these Terms and our <a href="{{ route('privacy') }}">Privacy Policy</a>. If you do not agree, do not use the service.</p><p>You must be at least 13 years old and meet any higher minimum age required where you live. If you have not reached the age of legal majority, your parent or guardian must approve your use where applicable.</p></section>
            <section id="account"><h2>2. Accounts and access</h2><p>Provide accurate information, keep it current and protect your login credentials. You are responsible for activity under your account and must promptly report suspected unauthorised access. You may not impersonate another person, create deceptive accounts, sell or transfer an account, or use the service after suspension without permission.</p><p>Some features require email verification, an accepted friendship, community membership or an approved application. Access to a community does not guarantee that submitted content will be published.</p></section>
            <section id="conduct"><h2>3. Community conduct</h2><p>Use {{ $productName }} with honesty, care and respect. You must not create, upload, send, promote or coordinate:</p><ul><li>Harassment, bullying, threats, stalking, hate speech or discrimination.</li><li>Sexual exploitation, child sexual abuse material, grooming or content that endangers minors.</li><li>Non-consensual intimate content, sexual solicitation or graphic sexual material.</li><li>Violence, credible threats, encouragement of self-harm or instructions facilitating serious harm.</li><li>Fraud, scams, spam, malicious links, impersonation or deceptive schemes.</li><li>Unlawful content, infringement of intellectual-property or privacy rights, or disclosure of another person’s confidential information.</li><li>Malware, automated scraping, unauthorised access, interference with service operation or attempts to bypass safety controls.</li></ul><p>Do not misuse faith, relationship or personal-growth discussions to manipulate, shame, exploit or pressure others. Respect blocks, declined requests, community boundaries and member consent.</p></section>
            <section id="content"><h2>4. Your content and permissions</h2><p>You retain ownership of content you create. You grant us a worldwide, non-exclusive, royalty-free licence to host, store, reproduce, process, display and distribute that content only as needed to operate, secure, moderate and improve {{ $productName }}. This licence ends when content is deleted from our active systems, except where copies must remain for backups, legal compliance, safety, or because other members have independently shared or stored it.</p><p>You confirm that you have the rights and permissions needed for everything you submit. You are responsible for your content and interactions. Saved posts, reposts and screenshots may allow content to persist beyond its original audience.</p></section>
            <section id="moderation"><h2>5. Moderation and reporting</h2><p>We may review, restrict, reject, remove or preserve content and may warn, suspend or terminate accounts when reasonably necessary to enforce these Terms, community requirements or law. Community leaders may review applications, members and submitted posts within their assigned communities.</p><p>Moderation is a safety tool, not a guarantee that all content will be reviewed or that objectionable content will never appear. Use available blocking and reporting or support tools when you experience a problem. We may report apparent criminal activity or imminent safety threats to appropriate authorities.</p></section>
            <section id="privacy"><h2>6. Privacy, personal safety and relationships</h2><p>Our <a href="{{ route('privacy') }}">Privacy Policy</a> explains how information is handled. Profile privacy and blocking tools reduce visibility or contact but cannot prevent others from recording or sharing information they can see. Think carefully before sharing sensitive personal, relationship, financial, health or location information.</p><p>{{ $productName }} facilitates social connection but does not verify every statement or guarantee another member’s identity, intentions, beliefs or conduct. Exercise judgment before meeting anyone offline and use appropriate personal-safety precautions.</p></section>
            <section id="service"><h2>7. The service and third parties</h2><p>We may add, change, pause or discontinue features, communities or content. Availability may be interrupted by maintenance, connectivity, security events or circumstances outside our control. Links or services provided by third parties are governed by their own terms and policies.</p><p>Faith, relationship, community and personal-growth content is provided for general discussion and encouragement. It is not a substitute for professional medical, mental-health, legal, financial, safeguarding or emergency advice.</p></section>
            <section id="termination"><h2>8. Suspension, termination and account deletion</h2><p>You may stop using the service and delete your account through Profile settings. We may restrict, suspend or terminate access for violations, risk to members or the service, legal requirements, prolonged inactivity, or discontinuation of the service. Where appropriate, we may provide notice or an opportunity to contact support, but immediate action may be necessary for serious safety or security concerns.</p></section>
            <section id="liability"><h2>9. Disclaimers and responsibility</h2><p>To the extent permitted by law, the service is provided “as is” and “as available”. We do not guarantee uninterrupted operation, specific outcomes, or the accuracy of member content. We are not responsible for member conduct or content beyond obligations that cannot legally be excluded.</p><p>Nothing in these Terms excludes rights or liabilities that applicable law does not allow us to exclude. To the extent permitted by law, {{ $brandName }} will not be liable for indirect, incidental, special or consequential losses arising from use of the service.</p></section>
            <section id="changes"><h2>10. Changes, governing law and contact</h2><p>We may update these Terms to reflect service, safety or legal changes. We will post the updated version, change the effective date and provide additional notice for material changes. Continued use after the effective date means you accept the revised Terms.</p><p>The governing law and courts will be those applicable to the entity operating {{ $brandName }} and your non-waivable consumer rights. This clause should be updated with the operator’s registered jurisdiction before public launch.</p><div class="contact"><p>Questions or concerns: <a href="mailto:{{ $supportEmail }}">{{ $supportEmail }}</a></p></div></section>
        @endif
        </article>
    </div>
</main>
<footer><div class="wrap footer"><span>© {{ date('Y') }} {{ $brandName }}. All rights reserved.</span><span><a href="{{ route('privacy') }}">Privacy Policy</a> · <a href="{{ route('terms') }}">Terms &amp; Conditions</a></span></div></footer>
</body>
</html>
