@php
    $brandName = \App\Models\PlatformSetting::valueFor('brand_name', config('branding.name'));
    $productName = \App\Models\PlatformSetting::valueFor('product_name', config('branding.product_name'));
    $supportEmail = \App\Models\PlatformSetting::valueFor('support_email', config('branding.support_email'));
    $androidAppUrl = 'https://play.google.com/store/apps/details?id=com.lstsocial.com';
@endphp
<!doctype html>
<html lang="en" class="scroll-smooth">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="description" content="LST Social is a thoughtful faith-centered community for genuine connection, encouragement and growth.">
    <title>{{ $productName }} · Faith, connection and growth</title>
    @vite(['resources/css/app.css'])
</head>
<body class="bg-white font-sans text-slate-900 antialiased">
    <header class="mx-auto flex h-20 w-[min(1160px,calc(100%-2rem))] items-center justify-between gap-5 sm:h-24 sm:w-[min(1160px,calc(100%-3rem))]">
        <a href="/" class="shrink-0" aria-label="{{ $brandName }} home"><img src="{{ asset('images/brand-logo.png') }}" alt="{{ $brandName }}" class="h-14 w-40 object-contain object-left sm:h-16 sm:w-44"></a>
        <nav class="flex items-center gap-2 sm:gap-7" aria-label="Main navigation"><div class="hidden items-center gap-7 text-sm font-semibold text-slate-500 lg:flex"><a href="#features" class="transition hover:text-[#e4002b]">Features</a><a href="#community" class="transition hover:text-[#e4002b]">Community</a><a href="#how-it-works" class="transition hover:text-[#e4002b]">How it works</a><a href="#values" class="transition hover:text-[#e4002b]">Safety</a></div><a href="#download" class="inline-flex min-h-11 items-center justify-center rounded-xl bg-[#e4002b] px-4 text-sm font-extrabold text-white shadow-lg shadow-red-200 transition hover:-translate-y-0.5 hover:bg-[#b90022] sm:px-5">Get the app</a></nav>
    </header>
    <main>
        <section class="hero relative isolate overflow-hidden bg-[#081a31] text-white"><video class="absolute inset-0 -z-20 h-full w-full object-cover object-center opacity-70" autoplay muted loop playsinline preload="metadata" aria-hidden="true"><source src="{{ asset('videos/community-hero.mp4') }}" type="video/mp4"></video><div class="absolute inset-0 -z-10 bg-[linear-gradient(90deg,rgba(5,18,37,.98)_0%,rgba(8,25,48,.9)_48%,rgba(8,25,48,.45)_100%)]"></div><div class="mx-auto grid min-h-[650px] w-[min(1160px,calc(100%-2rem))] items-center gap-10 py-14 sm:w-[min(1160px,calc(100%-3rem))] sm:py-20 lg:grid-cols-[1.05fr_.95fr] lg:gap-16 lg:py-16">
            <div><span class="inline-flex items-center gap-2 rounded-full border border-white/15 bg-white/10 px-3 py-2 text-[11px] font-extrabold uppercase tracking-[.12em] text-white backdrop-blur-md"><span class="h-2 w-2 rounded-full bg-[#ff496b] shadow-[0_0_0_5px_rgba(255,70,104,.15)]"></span>A faith-centred social community</span><h1 class="mt-6 max-w-3xl text-5xl font-black leading-[.98] tracking-[-.06em] text-white sm:text-6xl lg:text-7xl">Real conversations. Genuine people. <span class="text-[#ff496b]">Purposeful growth.</span></h1><p class="mt-6 max-w-2xl text-base leading-7 text-slate-200 sm:text-lg">{{ $productName }} is a welcoming mobile community from {{ $brandName }}, created for people who want more from social media: honest conversations, meaningful friendships and practical encouragement for everyday life.</p><p class="mt-5 max-w-xl border-l-[3px] border-[#ff496b] pl-4 text-sm leading-6 text-slate-300">Share what is on your heart, learn from other people's experiences and find communities where you can belong without the pressure, noise or performance of traditional social platforms.</p><div class="mt-8 flex flex-wrap gap-3"><a href="#features" class="inline-flex min-h-12 items-center justify-center rounded-xl bg-white px-5 text-sm font-extrabold text-[#0b1f3a] shadow-xl shadow-black/10 transition hover:-translate-y-0.5 hover:bg-slate-100">Explore the experience <span class="ml-2">→</span></a></div><div id="download" class="mt-5 flex flex-wrap gap-3"><span class="flex min-h-14 min-w-44 items-center gap-3 rounded-2xl border border-white/10 bg-black/30 px-4 text-white backdrop-blur-sm"><span class="text-2xl">●</span><span><small class="block text-[9px] font-bold uppercase tracking-[.12em] text-slate-300">iOS app</small><strong class="mt-0.5 block text-sm">Coming soon</strong></span></span><a class="flex min-h-14 min-w-44 items-center gap-3 rounded-2xl bg-white px-4 text-[#0b1f3a] shadow-xl transition hover:-translate-y-0.5" href="{{ $androidAppUrl }}" target="_blank" rel="noopener"><span class="text-2xl">▶</span><span><small class="block text-[9px] font-bold uppercase tracking-[.12em] text-slate-500">Get it on</small><strong class="mt-0.5 block text-sm">Google Play</strong></span></a></div><div class="mt-6 flex flex-wrap gap-x-5 gap-y-2 text-xs font-bold text-slate-300"><span><b class="mr-1 text-[#ff496b]">✓</b>Free to join</span><span><b class="mr-1 text-[#ff496b]">✓</b>Moderated communities</span><span><b class="mr-1 text-[#ff496b]">✓</b>Private messaging</span></div></div>
            <div class="relative hidden place-items-center lg:grid" aria-label="Preview of the LST Social mobile application"><div class="absolute h-[25rem] w-[25rem] rounded-full bg-gradient-to-br from-blue-400/10 to-red-500/20 blur-sm"></div><div class="relative w-[min(340px,90%)] rotate-2 rounded-[3rem] border-[10px] border-slate-950 bg-slate-50 px-4 pb-6 pt-5 shadow-[0_35px_85px_rgba(0,0,0,.35)]"><div class="absolute left-1/2 top-[-2px] h-6 w-24 -translate-x-1/2 rounded-b-2xl bg-slate-950"></div><div class="flex items-center gap-2.5 px-1 pb-5 pt-4"><span class="grid h-10 w-10 place-items-center rounded-xl bg-[#e4002b] text-[11px] font-black text-white">LST</span><div><strong class="block text-sm text-[#0b1f3a]">{{ $productName }}</strong><small class="text-xs text-slate-400">Your community is here</small></div></div><div class="rounded-[1.35rem] bg-gradient-to-br from-[#173a63] to-[#e4002b] p-5 text-white shadow-lg shadow-blue-900/20"><small class="text-[9px] font-extrabold tracking-[.12em]">TODAY'S ENCOURAGEMENT</small><p class="my-3 text-lg font-bold leading-snug">“Let all that you do be done in love.”</p><small class="text-[9px] font-extrabold tracking-[.12em]">1 CORINTHIANS 16:14</small></div><div class="mt-3 rounded-2xl border border-slate-200 bg-white p-3 text-xs text-slate-400">Share a thought, update or photo…</div><div class="mt-3 rounded-2xl border border-slate-200 bg-white p-3"><div class="flex items-center gap-2"><span class="grid h-9 w-9 place-items-center rounded-full bg-blue-50 text-[10px] font-extrabold text-[#0b1f3a]">AO</span><div><strong class="block text-xs">A community of care</strong><small class="text-[9px] text-slate-400">A few moments ago</small></div></div><p class="my-3 text-xs leading-5 text-slate-600">Growth becomes more meaningful when we walk alongside people who encourage honesty, grace and purpose.</p><div class="flex gap-5 border-t border-slate-100 pt-2 text-[10px] font-bold text-slate-500"><span>♡ Like</span><span>○ Comment</span><span>↗ Repost</span></div></div></div></div>
        </div><button class="video-control absolute bottom-5 right-5 grid h-10 w-10 place-items-center rounded-full border border-white/25 bg-black/30 text-sm text-white backdrop-blur-md" type="button" aria-label="Pause background video" aria-pressed="false">Ⅱ</button><a class="absolute bottom-5 left-5 text-[10px] text-white/60 transition hover:text-white" href="https://www.pexels.com/video/a-group-of-people-talking-7335879/" target="_blank" rel="noopener">Video by cottonbro studio · Pexels</a></section>

        <section id="features" class="bg-slate-50 py-20 sm:py-24"><div class="mx-auto w-[min(1160px,calc(100%-2rem))] sm:w-[min(1160px,calc(100%-3rem))]"><div class="max-w-2xl"><span class="text-xs font-extrabold uppercase tracking-[.14em] text-[#e4002b]">Inside {{ $productName }}</span><h2 class="mt-3 text-4xl font-black leading-tight tracking-[-.04em] text-[#0b1f3a] sm:text-5xl">More than a feed. A complete social experience.</h2><p class="mt-4 text-base leading-7 text-slate-500">Follow the conversations that matter to you, discover people and communities, and keep every connection organized as your network grows.</p></div><div class="mt-11 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">@foreach ([['▤','Personalized social feed','Publish text and photo posts, like, comment, reply, repost and save posts for later.'],['◎','Communities that fit you','Browse communities, apply or join, meet members and take part in focused discussions.'],['◇','Friends and discovery','Search for members, view profiles, send or accept friend requests and manage your connections.'],['✉','One-to-one conversations','Message friends privately, see unread activity and move through long chat histories efficiently.'],['♧','Quizzes and guided learning','Take community quizzes and learning activities that turn helpful ideas into practical reflection.'],['⌁','Notifications and saved posts','Return directly to relevant posts, profiles and chats, then revisit useful content anytime.']] as $feature)<article class="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm transition hover:-translate-y-1 hover:shadow-xl hover:shadow-slate-200/70"><div class="grid h-12 w-12 place-items-center rounded-2xl bg-blue-50 text-xl text-[#0b1f3a]">{{ $feature[0] }}</div><h3 class="mt-5 text-lg font-extrabold text-[#0b1f3a]">{{ $feature[1] }}</h3><p class="mt-2 text-sm leading-6 text-slate-500">{{ $feature[2] }}</p></article>@endforeach</div></div></section>

        <section id="community" class="py-20 sm:py-24"><div class="mx-auto grid w-[min(1160px,calc(100%-2rem))] items-start gap-12 sm:w-[min(1160px,calc(100%-3rem))] lg:grid-cols-[.9fr_1.1fr] lg:gap-20"><div><div class="max-w-xl"><span class="text-xs font-extrabold uppercase tracking-[.14em] text-[#e4002b]">A place to belong</span><h2 class="mt-3 text-4xl font-black leading-tight tracking-[-.04em] text-[#0b1f3a] sm:text-5xl">Social media can feel human again.</h2></div><p class="mt-6 text-base leading-8 text-slate-500">We believe the best online spaces do more than keep people scrolling. They help people feel seen, heard and supported. {{ $productName }} brings together community, conversation and personal growth in one carefully moderated experience.</p><p class="mt-4 text-base leading-8 text-slate-500">Whether you are navigating relationships, family life, faith, personal development or simply looking for thoughtful people to talk to, you can participate in a way that feels comfortable to you.</p></div><div class="grid gap-3 sm:grid-cols-2">@foreach ([['For honest conversations','Talk about real life with people who value empathy, respect and thoughtful responses.'],['For lasting friendships','Discover people with shared values and build connections at a natural, intentional pace.'],['For shared interests','Join focused communities where relevant experiences, questions and ideas can be explored.'],['For personal growth','Find encouragement, guided learning and practical insights you can carry into daily life.']] as $audience)<article class="rounded-2xl border border-rose-100 bg-[#fff9f7] p-5"><strong class="block text-[#0b1f3a]">{{ $audience[0] }}</strong><p class="mt-2 text-sm leading-6 text-slate-500">{{ $audience[1] }}</p></article>@endforeach</div></div></section>

        <section id="how-it-works" class="bg-slate-50 py-20 sm:py-24"><div class="mx-auto w-[min(1160px,calc(100%-2rem))] sm:w-[min(1160px,calc(100%-3rem))]"><div class="max-w-2xl"><span class="text-xs font-extrabold uppercase tracking-[.14em] text-[#e4002b]">Simple from the first tap</span><h2 class="mt-3 text-4xl font-black leading-tight tracking-[-.04em] text-[#0b1f3a] sm:text-5xl">Your LST Social journey.</h2><p class="mt-4 text-base leading-7 text-slate-500">Create your profile, find your people and participate at your own pace. Every area is built for mobile, including slow or interrupted internet connections.</p></div><div class="mt-11 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">@foreach ([['01','Create your profile','Sign up, verify your email and introduce yourself with the details you are comfortable sharing.'],['02','Discover people','Search members, send friend requests and build mutual connections before starting private chats.'],['03','Find your community','Browse focused groups, answer application questions where required and join relevant conversations.'],['04','Share and grow','Post, respond, save useful ideas, complete quizzes and stay informed through notifications.']] as $step)<article class="rounded-b-3xl border-t-4 border-[#e4002b] bg-white p-6 shadow-sm"><b class="text-xs tracking-[.14em] text-[#e4002b]">{{ $step[0] }}</b><h3 class="mt-4 text-lg font-extrabold text-[#0b1f3a]">{{ $step[1] }}</h3><p class="mt-2 text-sm leading-6 text-slate-500">{{ $step[2] }}</p></article>@endforeach</div></div></section>

        <section id="values" class="py-20 sm:py-24"><div class="mx-auto grid w-[min(1160px,calc(100%-2rem))] items-center gap-10 sm:w-[min(1160px,calc(100%-3rem))] lg:grid-cols-[.8fr_1.2fr] lg:gap-20"><div class="rounded-[2rem] bg-[#0b1f3a] p-8 text-white shadow-2xl shadow-blue-950/15 sm:p-10"><p class="text-2xl font-bold leading-relaxed">“A community becomes transformative when people feel safe enough to be honest and supported enough to grow.”</p><small class="mt-5 block text-slate-300">Love Straight Talks</small></div><div><div class="max-w-xl"><span class="text-xs font-extrabold uppercase tracking-[.14em] text-[#e4002b]">Our foundation</span><h2 class="mt-3 text-4xl font-black leading-tight tracking-[-.04em] text-[#0b1f3a] sm:text-5xl">Connection with care and accountability.</h2></div><div class="mt-8 space-y-3">@foreach ([['Safety by design','Community applications, moderation and relationship controls protect meaningful participation.'],['Privacy with purpose','Members control their profiles and connect intentionally before messaging.'],['Growth over noise','Every feature supports healthy relationships, learning and genuine encouragement.']] as $value)<div class="flex gap-4 rounded-2xl border border-slate-200 p-5"><i class="grid h-8 w-8 shrink-0 place-items-center rounded-xl bg-green-50 text-sm font-black not-italic text-green-700">✓</i><div><strong class="block text-[#0b1f3a]">{{ $value[0] }}</strong><small class="mt-1 block leading-6 text-slate-500">{{ $value[1] }}</small></div></div>@endforeach</div></div></div></section>

        <section class="pb-20 sm:pb-24"><div class="mx-auto w-[min(1160px,calc(100%-2rem))] sm:w-[min(1160px,calc(100%-3rem))]"><div class="relative isolate overflow-hidden rounded-[2rem] bg-gradient-to-br from-[#0b1f3a] to-[#173f6d] px-6 py-14 text-center text-white sm:px-12"><div class="absolute -right-24 -top-32 -z-10 h-64 w-64 rounded-full bg-[#e4002b]/30"></div><h2 class="text-4xl font-black tracking-[-.04em] sm:text-5xl">Come grow with a community that cares.</h2><p class="mx-auto mt-4 max-w-2xl text-base leading-7 text-slate-300">Download {{ $productName }} and join a protected space for conversations that matter and relationships that help people flourish.</p><div class="mt-7 flex flex-wrap justify-center gap-3"><span class="flex min-h-14 min-w-44 items-center gap-3 rounded-2xl border border-white/15 bg-white/10 px-4 text-left"><span class="text-2xl">●</span><span><small class="block text-[9px] font-bold uppercase tracking-[.12em] text-slate-300">iOS app</small><strong class="mt-0.5 block text-sm">Coming soon</strong></span></span><a href="{{ $androidAppUrl }}" target="_blank" rel="noopener" class="flex min-h-14 min-w-44 items-center gap-3 rounded-2xl bg-white px-4 text-left text-[#0b1f3a] transition hover:-translate-y-0.5"><span class="text-2xl">▶</span><span><small class="block text-[9px] font-bold uppercase tracking-[.12em] text-slate-500">Get it on</small><strong class="mt-0.5 block text-sm">Google Play</strong></span></a></div></div></div></section>
    </main>
    <footer class="border-t border-slate-200 py-8"><div class="mx-auto flex w-[min(1160px,calc(100%-2rem))] flex-col gap-4 text-xs text-slate-500 sm:w-[min(1160px,calc(100%-3rem))] sm:flex-row sm:items-center sm:justify-between"><span>© {{ date('Y') }} {{ $brandName }}. All rights reserved.</span><div><a class="font-bold text-[#0b1f3a] hover:text-[#e4002b]" href="{{ route('privacy') }}">Privacy Policy</a> <span class="mx-1">·</span> <a class="font-bold text-[#0b1f3a] hover:text-[#e4002b]" href="{{ route('terms') }}">Terms &amp; Conditions</a> <span class="mx-1">·</span> Need help? <a class="font-bold text-[#0b1f3a] hover:text-[#e4002b]" href="mailto:{{ $supportEmail }}">{{ $supportEmail }}</a></div></div></footer>
    <script>
        const heroVideo = document.querySelector('.hero video');
        const videoControl = document.querySelector('.video-control');
        heroVideo?.play().catch(() => { videoControl.textContent = '▶'; videoControl.setAttribute('aria-label', 'Play background video'); videoControl.setAttribute('aria-pressed', 'true'); });
        heroVideo?.addEventListener('error', () => { videoControl.hidden = true; });
        videoControl?.addEventListener('click', () => { if (heroVideo.paused) { heroVideo.play(); videoControl.textContent = 'Ⅱ'; videoControl.setAttribute('aria-label', 'Pause background video'); videoControl.setAttribute('aria-pressed', 'false'); } else { heroVideo.pause(); videoControl.textContent = '▶'; videoControl.setAttribute('aria-label', 'Play background video'); videoControl.setAttribute('aria-pressed', 'true'); } });
    </script>
</body>
</html>
