@php
    $brandName = \App\Models\PlatformSetting::valueFor('brand_name', config('branding.name'));
    $productName = \App\Models\PlatformSetting::valueFor('product_name', config('branding.product_name'));
    $supportEmail = \App\Models\PlatformSetting::valueFor('support_email', config('branding.support_email'));
    $iosAppUrl = \App\Models\PlatformSetting::valueFor('ios_app_url', config('branding.ios_app_url'));
    $androidAppUrl = \App\Models\PlatformSetting::valueFor('android_app_url', config('branding.android_app_url'));
@endphp
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="description" content="LST Social is a thoughtful faith-centered community for genuine connection, encouragement and growth.">
    <title>{{ $productName }} · Faith, connection and growth</title>
    <style>
        :root{--navy:#0b1f3a;--navy2:#173a63;--red:#e4002b;--red-dark:#b90022;--red-soft:#fff0f3;--cream:#fff9f7;--ink:#101828;--muted:#667085;--line:#e8e9ed;--white:#fff;--soft:#f3f6fa;--green:#166534;--shadow:0 24px 70px rgba(11,31,58,.13)}
        *{box-sizing:border-box}html{scroll-behavior:smooth}body{margin:0;color:var(--ink);font-family:Inter,ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;background:var(--white)}a{color:inherit}.wrap{width:min(1160px,calc(100% - 40px));margin:auto}.nav{height:88px;display:flex;align-items:center;justify-content:space-between;gap:20px}.brand{display:flex;align-items:center;text-decoration:none}.brand img{width:178px;height:62px;object-fit:contain;object-position:left center}.nav-links{display:flex;align-items:center;gap:26px}.nav-links>a:not(.button){text-decoration:none;font-size:14px;font-weight:650;color:#475467}.button{display:inline-flex;align-items:center;justify-content:center;min-height:48px;padding:0 20px;border-radius:14px;text-decoration:none;font-size:14px;font-weight:800;border:1px solid transparent;transition:.2s transform,.2s box-shadow}.button:hover{transform:translateY(-2px)}.primary{background:var(--red);color:#fff;box-shadow:0 10px 24px rgba(228,0,43,.2)}.primary:hover{background:var(--red-dark)}.secondary{border-color:#d9dee7;background:#fff;color:var(--navy)}
        .hero{position:relative;overflow:hidden;background:linear-gradient(145deg,#fff 0%,var(--cream) 48%,#f3f7fb 100%);border-top:1px solid #f1f2f4}.hero:before{content:"";position:absolute;width:520px;height:520px;border-radius:50%;background:rgba(228,0,43,.08);right:-230px;top:-170px}.hero-grid{min-height:680px;display:grid;grid-template-columns:1.05fr .95fr;align-items:center;gap:70px;padding:72px 0 88px}.eyebrow{display:inline-flex;align-items:center;gap:9px;padding:8px 12px;border-radius:999px;background:var(--red-soft);color:var(--red-dark);font-size:12px;font-weight:850;letter-spacing:.06em;text-transform:uppercase}.eyebrow:before{content:"";width:7px;height:7px;border-radius:50%;background:var(--red)}h1{font-size:clamp(43px,6vw,72px);line-height:1.02;letter-spacing:-.055em;margin:24px 0 20px;color:var(--navy);max-width:720px}h1 em{font-style:normal;color:var(--red)}.lead{font-size:18px;line-height:1.75;color:#536174;max-width:640px}.hero-note{max-width:620px;margin:16px 0 0;padding-left:16px;border-left:3px solid var(--red);color:#667085;font-size:14px;line-height:1.7}.hero-brand{width:min(310px,70vw);height:auto;margin-bottom:20px}.hero-actions{display:flex;flex-wrap:wrap;gap:12px;margin-top:32px}.store-actions{display:flex;flex-wrap:wrap;gap:11px;margin-top:17px}.store-button{min-width:190px;min-height:59px;display:flex;align-items:center;gap:12px;padding:8px 17px;border-radius:15px;background:#0d1117;color:#fff;text-decoration:none;box-shadow:0 11px 24px rgba(13,17,23,.16);transition:.2s transform}.store-button:hover{transform:translateY(-2px)}.store-icon{font-size:27px;line-height:1}.store-button small{display:block;font-size:9px;letter-spacing:.08em;text-transform:uppercase;color:#cbd5e1}.store-button strong{display:block;font-size:16px;margin-top:2px}.trust{display:flex;flex-wrap:wrap;gap:18px;margin-top:30px;color:#667085;font-size:13px;font-weight:650}.trust span:before{content:"✓";color:var(--red);font-weight:900;margin-right:7px}
        .phone-stage{position:relative;display:grid;place-items:center}.glow{position:absolute;width:390px;height:390px;border-radius:50%;background:linear-gradient(135deg,rgba(23,58,99,.18),rgba(214,40,57,.16));filter:blur(4px)}.phone{position:relative;width:min(340px,90%);background:#f7f8fb;border:10px solid #111827;border-radius:48px;padding:20px 16px 24px;box-shadow:0 35px 85px rgba(11,31,58,.28);transform:rotate(2deg)}.phone:before{content:"";display:block;width:92px;height:22px;border-radius:0 0 14px 14px;background:#111827;position:absolute;top:-2px;left:50%;transform:translateX(-50%)}.app-head{display:flex;align-items:center;gap:10px;padding:16px 3px 18px}.app-mark{width:39px;height:39px;border-radius:12px;display:grid;place-items:center;background:var(--red);color:#fff;font-size:11px;font-weight:900;letter-spacing:-.03em}.app-head strong{display:block;color:var(--navy)}.app-head small{color:#7b8492}.encouragement{padding:20px;border-radius:21px;color:#fff;background:linear-gradient(135deg,var(--navy2),var(--red));box-shadow:0 16px 30px rgba(23,58,99,.2)}.encouragement small{font-size:9px;font-weight:800;letter-spacing:.1em}.encouragement p{font-size:19px;line-height:1.45;margin:12px 0 8px;font-weight:750}.composer,.post{background:#fff;border:1px solid #e7eaf0;border-radius:17px;margin-top:12px;padding:13px}.composer{color:#8a93a1;font-size:12px}.post-top{display:flex;align-items:center;gap:9px}.avatar{width:35px;height:35px;border-radius:50%;display:grid;place-items:center;background:#e8eef6;color:var(--navy);font-size:10px;font-weight:850}.post-top strong{font-size:12px}.post-top small{display:block;color:#8a93a1;font-size:9px}.post>p{font-size:12px;line-height:1.55;color:#4e5968}.post-meta{display:flex;gap:20px;border-top:1px solid #eef0f3;padding-top:10px;color:#6b7482;font-size:10px;font-weight:700}
        section{padding:95px 0}.section-head{max-width:700px;margin-bottom:44px}.section-head span{color:var(--red);font-size:12px;font-weight:850;text-transform:uppercase;letter-spacing:.1em}.section-head h2{font-size:clamp(32px,4vw,48px);letter-spacing:-.04em;line-height:1.08;margin:12px 0;color:var(--navy)}.section-head p{font-size:16px;line-height:1.7;color:var(--muted)}.features{background:#f7f9fb}.feature-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:18px}.feature{background:#fff;border:1px solid var(--line);border-radius:22px;padding:26px;box-shadow:0 8px 25px rgba(16,24,40,.04)}.feature-icon{width:46px;height:46px;border-radius:14px;display:grid;place-items:center;background:#edf2f8;color:var(--navy);font-size:21px}.feature:nth-child(2) .feature-icon,.feature:nth-child(5) .feature-icon{background:var(--red-soft);color:var(--red)}.feature h3{margin:20px 0 8px;font-size:18px;color:var(--navy)}.feature p{margin:0;color:var(--muted);line-height:1.65;font-size:14px}
        .values{display:grid;grid-template-columns:.8fr 1.2fr;gap:70px;align-items:center}.quote{background:var(--navy);color:#fff;border-radius:30px;padding:38px;box-shadow:var(--shadow)}.quote p{font-size:25px;line-height:1.5;margin:0}.quote small{display:block;margin-top:18px;color:#b7c4d5}.value-list{display:grid;gap:12px}.value-row{display:flex;gap:15px;padding:19px;border:1px solid var(--line);border-radius:17px}.value-row i{width:30px;height:30px;border-radius:10px;background:#eaf8ef;color:#15803d;display:grid;place-items:center;font-style:normal;font-weight:900;flex:0 0 auto}.value-row strong{display:block;color:var(--navy)}.value-row small{display:block;color:var(--muted);line-height:1.55;margin-top:4px}.journey{display:grid;grid-template-columns:repeat(4,1fr);gap:18px}.step{position:relative;padding:26px 22px;border-top:3px solid var(--red);background:#fff;border-radius:0 0 20px 20px;box-shadow:0 10px 30px rgba(16,24,40,.06)}.step b{display:block;color:var(--red);font-size:12px;letter-spacing:.08em;margin-bottom:12px}.step h3{color:var(--navy);margin:0 0 8px;font-size:18px}.step p{color:var(--muted);font-size:14px;line-height:1.65;margin:0}.experience{background:var(--soft)}.belonging{display:grid;grid-template-columns:1.05fr .95fr;gap:54px;align-items:start}.belonging-copy p{color:var(--muted);font-size:16px;line-height:1.8}.audience-grid{display:grid;grid-template-columns:1fr 1fr;gap:14px}.audience{padding:22px;border-radius:18px;background:var(--cream);border:1px solid #f4dfe3}.audience strong{display:block;color:var(--navy);margin-bottom:7px}.audience p{margin:0;color:var(--muted);font-size:13px;line-height:1.6}
        .cta{padding-top:20px}.cta-box{position:relative;overflow:hidden;background:linear-gradient(135deg,var(--navy),#173f6d);color:#fff;border-radius:32px;padding:64px;text-align:center}.cta-box:after{content:"";position:absolute;width:260px;height:260px;border-radius:50%;background:rgba(228,0,43,.28);right:-100px;top:-130px}.cta-box h2{font-size:clamp(31px,4vw,48px);letter-spacing:-.04em;margin:0 0 14px}.cta-box p{color:#cbd5e1;font-size:16px;line-height:1.7;max-width:620px;margin:0 auto 28px}.cta-box .store-actions{justify-content:center}.cta-box .store-button{position:relative;z-index:1;background:#fff;color:var(--navy)}.cta-box .store-button small{color:#667085}footer{padding:36px 0;border-top:1px solid var(--line);margin-top:95px}.footer{display:flex;align-items:center;justify-content:space-between;gap:20px;color:#788292;font-size:13px}.footer a{text-decoration:none;color:var(--navy);font-weight:700}
        @media(max-width:900px){.hero-grid,.values,.belonging{grid-template-columns:1fr}.hero-grid{padding-top:55px}.phone-stage{margin-top:15px}.feature-grid,.journey{grid-template-columns:repeat(2,1fr)}.values{gap:35px}}
        @media(max-width:620px){.wrap{width:min(100% - 28px,1160px)}.nav-links>a:not(.button){display:none}.nav-links{gap:8px}.nav .button{min-height:42px;padding:0 13px}.hero-grid{min-height:auto;padding:50px 0 70px;gap:46px}.lead{font-size:16px}.phone{width:300px}.feature-grid,.journey,.audience-grid{grid-template-columns:1fr}section{padding:70px 0}.cta-box{padding:44px 22px}.footer{align-items:flex-start;flex-direction:column}.values{grid-template-columns:1fr}.quote{padding:28px}.quote p{font-size:21px}}
    </style>
</head>
<body>
<header class="wrap nav"><a class="brand" href="/"><img src="{{ asset('images/brand-logo.png') }}" alt="{{ $brandName }}"></a><nav class="nav-links"><a href="#features">Features</a><a href="#community">Community</a><a href="#how-it-works">How it works</a><a href="#values">Safety</a><a class="button primary" href="#download">Get the app</a></nav></header>
<main>
    <section class="hero"><div class="wrap hero-grid"><div><span class="eyebrow">A faith-centred social community</span><h1>Real conversations. Genuine people. <em>Purposeful growth.</em></h1><p class="lead">{{ $productName }} is a welcoming mobile community from {{ $brandName }}, created for people who want more from social media: honest conversations, meaningful friendships and practical encouragement for everyday life.</p><p class="hero-note">Share what is on your heart, learn from other people's experiences and find communities where you can belong without the pressure, noise or performance of traditional social platforms.</p><div class="hero-actions"><a class="button secondary" href="#features">Explore the experience</a></div><div class="store-actions" id="download"><a class="store-button" href="{{ $iosAppUrl }}" target="_blank" rel="noopener"><span class="store-icon">●</span><span><small>Download on the</small><strong>App Store</strong></span></a><a class="store-button" href="{{ $androidAppUrl }}" target="_blank" rel="noopener"><span class="store-icon">▶</span><span><small>Get it on</small><strong>Google Play</strong></span></a></div><div class="trust"><span>Free to join</span><span>Moderated communities</span><span>Private messaging</span></div></div>
    <div class="phone-stage" aria-label="Preview of the LST Social mobile application"><div class="glow"></div><div class="phone"><div class="app-head"><span class="app-mark">LST</span><div><strong>{{ $productName }}</strong><small>Your community is here</small></div></div><div class="encouragement"><small>TODAY'S ENCOURAGEMENT</small><p>“Let all that you do be done in love.”</p><small>1 CORINTHIANS 16:14</small></div><div class="composer">Share a thought, update or photo…</div><div class="post"><div class="post-top"><span class="avatar">AO</span><div><strong>A community of care</strong><small>A few moments ago</small></div></div><p>Growth becomes more meaningful when we walk alongside people who encourage honesty, grace and purpose.</p><div class="post-meta"><span>♡ Like</span><span>○ Comment</span><span>↗ Repost</span></div></div></div></div></div></section>
    <section class="features" id="features"><div class="wrap"><div class="section-head"><span>Inside {{ $productName }}</span><h2>More than a feed. A complete social experience.</h2><p>Follow the conversations that matter to you, discover people and communities, and keep every connection organized as your network grows.</p></div><div class="feature-grid">
        <article class="feature"><div class="feature-icon">▤</div><h3>Personalized social feed</h3><p>Publish text and photo posts, like, comment, reply, repost and save posts for later. Infinite scrolling keeps discovery smooth without loading everything at once.</p></article>
        <article class="feature"><div class="feature-icon">◎</div><h3>Communities that fit you</h3><p>Browse communities, apply or join, meet members and take part in focused discussions. Community owners can review members and moderate submitted posts.</p></article>
        <article class="feature"><div class="feature-icon">◇</div><h3>Friends and discovery</h3><p>Search for members, view profiles, send or accept friend requests and manage your connections with clear privacy controls.</p></article>
        <article class="feature"><div class="feature-icon">✉</div><h3>One-to-one conversations</h3><p>Message friends privately, see unread activity and move through long chat histories efficiently with paginated message loading.</p></article>
        <article class="feature"><div class="feature-icon">♧</div><h3>Quizzes and guided learning</h3><p>Take community quizzes and learning activities that turn helpful ideas into practical reflection, conversation and personal growth.</p></article>
        <article class="feature"><div class="feature-icon">⌁</div><h3>Notifications and saved posts</h3><p>Return directly to relevant posts, profiles and chats from notifications, then revisit useful content anytime from your saved collection.</p></article>
    </div></div></section>
    <section id="community"><div class="wrap belonging"><div class="belonging-copy"><div class="section-head"><span>A place to belong</span><h2>Social media can feel human again.</h2></div><p>We believe the best online spaces do more than keep people scrolling. They help people feel seen, heard and supported. {{ $productName }} brings together community, conversation and personal growth in one carefully moderated experience.</p><p>Whether you are navigating relationships, family life, faith, personal development or simply looking for thoughtful people to talk to, you can participate in a way that feels comfortable to you.</p></div><div class="audience-grid"><article class="audience"><strong>For honest conversations</strong><p>Talk about real life with people who value empathy, respect and thoughtful responses.</p></article><article class="audience"><strong>For lasting friendships</strong><p>Discover people with shared values and build connections at a natural, intentional pace.</p></article><article class="audience"><strong>For shared interests</strong><p>Join focused communities where relevant experiences, questions and ideas can be explored.</p></article><article class="audience"><strong>For personal growth</strong><p>Find encouragement, guided learning and practical insights you can carry into daily life.</p></article></div></div></section>
    <section class="experience" id="how-it-works"><div class="wrap"><div class="section-head"><span>Simple from the first tap</span><h2>Your LST Social journey.</h2><p>Create your profile, find your people and participate at your own pace. Every area is built for mobile, including slow or interrupted internet connections.</p></div><div class="journey"><article class="step"><b>01</b><h3>Create your profile</h3><p>Sign up, verify your email and introduce yourself with the details you are comfortable sharing.</p></article><article class="step"><b>02</b><h3>Discover people</h3><p>Search members, send friend requests and build mutual connections before starting private chats.</p></article><article class="step"><b>03</b><h3>Find your community</h3><p>Browse focused groups, answer application questions where required and join conversations relevant to you.</p></article><article class="step"><b>04</b><h3>Share and grow</h3><p>Post, respond, save useful ideas, complete quizzes and stay informed through targeted notifications.</p></article></div></div></section>
    <section id="values"><div class="wrap values"><div class="quote"><p>“A community becomes transformative when people feel safe enough to be honest and supported enough to grow.”</p><small>Love Straight Talks</small></div><div><div class="section-head"><span>Our foundation</span><h2>Connection with care and accountability.</h2></div><div class="value-list"><div class="value-row"><i>✓</i><div><strong>Safety by design</strong><small>Community applications, moderation and relationship controls protect meaningful participation.</small></div></div><div class="value-row"><i>✓</i><div><strong>Privacy with purpose</strong><small>Members control their profiles and connect intentionally before messaging.</small></div></div><div class="value-row"><i>✓</i><div><strong>Growth over noise</strong><small>Every feature supports healthy relationships, learning and genuine encouragement.</small></div></div></div></div></div></section>
    <section class="cta"><div class="wrap"><div class="cta-box"><h2>Come grow with a community that cares.</h2><p>Download {{ $productName }} and join a protected space for conversations that matter and relationships that help people flourish.</p><div class="store-actions"><a class="store-button" href="{{ $iosAppUrl }}" target="_blank" rel="noopener"><span class="store-icon">●</span><span><small>Download on the</small><strong>App Store</strong></span></a><a class="store-button" href="{{ $androidAppUrl }}" target="_blank" rel="noopener"><span class="store-icon">▶</span><span><small>Get it on</small><strong>Google Play</strong></span></a></div></div></div></section>
</main>
<footer><div class="wrap footer"><span>© {{ date('Y') }} {{ $brandName }}. All rights reserved.</span><div>Need help? <a href="mailto:{{ $supportEmail }}">{{ $supportEmail }}</a></div></div></footer>
</body></html>
