import React, { useState } from 'react';
import { ActivityIndicator, Alert, ScrollView, StyleSheet, Text, TextInput, TouchableOpacity } from 'react-native';
import apiService from '../../api/apiService';
import { useTheme } from '../../context/ThemeContext';

export default function FeedbackScreen({ route, navigation }) {
  const { theme } = useTheme(); const [type, setType] = useState(route.params?.type || 'feedback'); const [subject, setSubject] = useState(''); const [message, setMessage] = useState(''); const [sending, setSending] = useState(false);
  const submit = async () => { if (!subject.trim() || !message.trim()) return Alert.alert('Details required', 'Add a subject and message.'); setSending(true); try { await apiService.submitSupportRequest(type, subject.trim(), message.trim()); Alert.alert('Message received', 'Our support team will review it.', [{ text: 'Done', onPress: () => navigation.goBack() }]); } catch (error) { Alert.alert('Could not send', error.message); } finally { setSending(false); } };
  return <ScrollView style={{ backgroundColor: theme.background }} contentContainerStyle={styles.content}><Text style={[styles.label, { color: theme.secondaryText }]}>Message type</Text><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.types}>{[['feedback','Feedback'],['issue','Report issue'],['support','Support request']].map(([value,label]) => <TouchableOpacity key={value} onPress={() => setType(value)} style={[styles.type, { borderColor: type === value ? theme.primary : theme.border, backgroundColor: type === value ? theme.primarySoft : theme.card }]}><Text style={{ color: type === value ? theme.primary : theme.text, fontWeight: '700' }}>{label}</Text></TouchableOpacity>)}</ScrollView><Text style={[styles.label, { color: theme.secondaryText }]}>Subject</Text><TextInput value={subject} onChangeText={setSubject} style={[styles.input, { backgroundColor: theme.card, borderColor: theme.border, color: theme.text }]} placeholder="Brief summary" placeholderTextColor={theme.secondaryText} maxLength={150} /><Text style={[styles.label, { color: theme.secondaryText }]}>Message</Text><TextInput value={message} onChangeText={setMessage} style={[styles.input, styles.message, { backgroundColor: theme.card, borderColor: theme.border, color: theme.text }]} placeholder="Tell us what happened or how we can improve" placeholderTextColor={theme.secondaryText} multiline maxLength={5000} /><TouchableOpacity style={[styles.submit, { backgroundColor: theme.primary }]} onPress={submit} disabled={sending}>{sending ? <ActivityIndicator color="#fff" /> : <Text style={styles.submitText}>Send message</Text>}</TouchableOpacity></ScrollView>;
}
const styles = StyleSheet.create({ content: { padding: 18 }, label: { fontSize: 11, fontWeight: '800', textTransform: 'uppercase', marginBottom: 7, marginTop: 8 }, types: { gap: 7, marginBottom: 14 }, type: { paddingHorizontal: 13, paddingVertical: 10, borderWidth: 1, borderRadius: 999 }, input: { minHeight: 49, borderWidth: 1, borderRadius: 14, paddingHorizontal: 13, fontSize: 14, marginBottom: 14 }, message: { height: 190, paddingTop: 13, textAlignVertical: 'top' }, submit: { height: 54, borderRadius: 16, alignItems: 'center', justifyContent: 'center' }, submitText: { color: '#fff', fontWeight: '800' } });
