@if(session('status'))
    <div class="admin-notice">{{ session('status') }}</div>
@endif
@if($errors->any())
    <div class="admin-notice error">{{ $errors->first() }}</div>
@endif

@if($section === 'overview')
    @php
        $metricIcons = [
            'Total members' => '<circle cx="9" cy="8" r="4"/><path d="M2 21c.8-4 3.1-6 7-6s6.2 2 7 6M17 5c2.5.6 4 2.2 4 4.5S19.5 13.4 17 14"/>',
            'Communities' => '<path d="M4 21v-9l8-6 8 6v9M9 21v-6h6v6"/>',
            'Pending applications' => '<path d="M5 3h14v18H5zM8 8h8M8 12h8M8 16h5"/>',
            'Pending posts' => '<path d="M12 3 4 6v5c0 5.1 3.4 8.7 8 10 4.6-1.3 8-4.9 8-10V6zM9 12l2 2 4-5"/>',
        ];
    @endphp
    <div class="dashboard-welcome">
        <div><div class="eyebrow">{{ now()->format('l, d F Y') }}</div><h1>Welcome back, {{ explode(' ', auth()->user()->name)[0] }}</h1></div>
    </div>

    <section class="stats dashboard-stats">
        @foreach($overviewMetrics as $label=>$value)
            <article class="card stat dashboard-stat"><div class="stat-top"><span class="stat-icon {{ str_contains(strtolower($label), 'pending') ? 'red' : '' }}"><svg class="icon">{!! $metricIcons[$label] ?? '<path d="M4 20V10M10 20V4M16 20v-7"/>' !!}</svg></span><span class="metric-live"><i></i> Live</span></div><div class="stat-value">{{ number_format($value) }}</div><div class="stat-label">{{ $label }}</div></article>
        @endforeach
    </section>

    <section class="dashboard-grid">
        <article class="card panel dashboard-panel">
            <div class="panel-head"><div><h2>Newest members</h2><div class="panel-sub">The latest people to join LST Social</div></div><a class="panel-link" href="{{ url('/admin/members') }}">View all →</a></div>
            <div class="dashboard-list">@forelse($recentMembers as $member)<div class="dashboard-row"><div class="avatar">{{ strtoupper(substr($member->name,0,2)) }}</div><div class="dashboard-row-copy"><strong>{{ $member->name }}</strong><span>{{ $member->email }}</span></div><time>{{ $member->created_at->diffForHumans() }}</time></div>@empty<div class="dashboard-empty"><span>◎</span><strong>No members yet</strong><small>New accounts will appear here.</small></div>@endforelse</div>
        </article>
        <article class="card panel dashboard-panel">
            <div class="panel-head"><div><h2>Recent applications</h2><div class="panel-sub">Latest community membership requests</div></div><a class="panel-link" href="{{ url('/admin/moderation') }}">Review all →</a></div>
            <div class="dashboard-list">@forelse($recentApplications as $application)<div class="dashboard-row"><div class="avatar">{{ strtoupper(substr($application->user?->name ?? '?',0,2)) }}</div><div class="dashboard-row-copy"><strong>{{ $application->user?->name ?? 'Deleted member' }}</strong><span>{{ $application->community?->name ?? 'Unavailable community' }}</span></div><span class="admin-pill {{ $application->status }}">{{ ucfirst($application->status) }}</span></div>@empty<div class="dashboard-empty"><span>✓</span><strong>You are all caught up</strong><small>New applications will appear here.</small></div>@endforelse</div>
        </article>
    </section>
@elseif($section === 'members')
    <div class="page-heading"><div><div class="eyebrow">People & access</div><h1>Members</h1><p>Search profiles, review account details and manage member access.</p></div><details class="create-member"><summary class="btn btn-primary">+ Add member</summary><form class="admin-form compact floating-form" method="POST" action="{{ route('admin.members.store') }}">@csrf<label>Full name<input name="name" required></label><label>Email<input type="email" name="email" required></label><div class="form-grid"><label>Temporary password<input type="password" name="password" minlength="8" required></label><label>Confirm password<input type="password" name="password_confirmation" required></label></div><label>Role<select name="role">@foreach(['member','moderator','admin','super_admin'] as $role)<option value="{{ $role }}">{{ ucfirst(str_replace('_',' ',$role)) }}</option>@endforeach</select></label><label class="check-label"><input type="checkbox" name="email_verified" value="1"> Mark email verified</label><button class="btn btn-primary">Create account</button></form></details></div>
    <section class="stats">
        @foreach($memberMetrics as $label => $value)
            <article class="card stat"><div class="stat-top"><span class="stat-icon">{{ substr($label, 0, 1) }}</span><span class="trend">Live</span></div><div class="stat-value">{{ number_format($value) }}</div><div class="stat-label">{{ $label }}</div></article>
        @endforeach
    </section>
    <section class="card members-panel">
        <div class="members-toolbar"><div><h2>Member directory</h2><span><strong>{{ number_format($members->total()) }}</strong> matching account{{ $members->total() === 1 ? '' : 's' }}</span></div><form id="member-filter" method="GET" action="{{ url('/admin/members') }}" class="member-filter"><label class="member-search"><svg class="icon"><circle cx="11" cy="11" r="7"/><path d="m20 20-4-4"/></svg><input type="search" name="search" value="{{ $memberSearch }}" placeholder="Search name or email" autocomplete="off"></label><select name="role" aria-label="Filter by role"><option value="">All roles</option>@foreach(['member','moderator','admin','super_admin'] as $role)<option value="{{ $role }}" @selected($memberRole===$role)>{{ ucfirst(str_replace('_',' ',$role)) }}</option>@endforeach</select><select name="account_status" aria-label="Filter by account status"><option value="">All accounts</option><option value="active" @selected($memberAccountStatus==='active')>Active</option><option value="suspended" @selected($memberAccountStatus==='suspended')>Suspended</option></select><button class="mini-btn" type="submit">Apply</button>@if($memberSearch || $memberRole || $memberAccountStatus)<a class="clear-filter" href="{{ url('/admin/members') }}">Clear</a>@endif</form></div>
        <div class="admin-table-wrap"><table class="admin-table">
            <thead><tr><th>Member</th><th>Status</th><th>Role</th><th>Communities</th><th>Joined</th><th></th></tr></thead>
            <tbody>
            @forelse($members as $member)
                <tr>
                    <td><div class="table-person"><div class="avatar">{{ strtoupper(substr($member->name,0,2)) }}</div><div><strong>{{ $member->name }}</strong><small>{{ $member->email }}</small></div></div></td>
                    <td><span class="account-status {{ $member->suspended_at ? 'suspended' : 'active' }}"><i></i>{{ $member->suspended_at ? 'Suspended' : 'Active' }}</span></td>
                    <td><span class="admin-pill">{{ ucfirst(str_replace('_', ' ', $member->role ?: 'member')) }}</span></td>
                    <td>{{ $member->communities_count }}</td><td>{{ $member->created_at->format('d M Y') }}</td>
                    <td><a class="member-view-btn" href="{{ route('admin.members.show', $member) }}">View details <span>→</span></a></td>
                </tr>
            @empty<tr><td colspan="6" class="empty-cell">No members match your search and filters.</td></tr>@endforelse
            </tbody>
        </table></div>
        @if($members->hasPages())<nav class="admin-pagination" aria-label="Member pages">@if($members->onFirstPage())<span>← Previous</span>@else<a href="{{ $members->previousPageUrl() }}">← Previous</a>@endif<strong>Page {{ $members->currentPage() }} of {{ $members->lastPage() }}</strong>@if($members->hasMorePages())<a href="{{ $members->nextPageUrl() }}">Next →</a>@else<span>Next →</span>@endif</nav>@endif
    </section>
@elseif($section === 'communities')
    <div class="page-heading"><div><div class="eyebrow">Spaces & membership</div><h1>Communities</h1><p>Manage community details, assign owners and review membership applications.</p></div></div>
    <section class="stats">
        @foreach($communityMetrics as $label => $value)
            <article class="card stat"><div class="stat-top"><span class="stat-icon">{{ substr($label, 0, 1) }}</span><span class="trend">Live</span></div><div class="stat-value">{{ number_format($value) }}</div><div class="stat-label">{{ $label }}</div></article>
        @endforeach
    </section>
    <section class="card panel">
        <div class="panel-head"><div><h2>Community directory</h2><div class="panel-sub">Edit details, rules, owners and visibility from one place.</div></div><details><summary class="mini-btn">New community</summary><form class="admin-form compact" method="POST" action="{{ route('admin.communities.store') }}" enctype="multipart/form-data">@csrf<label>Name<input name="name" required></label><label>Description<textarea name="description"></textarea></label><label>Rules<textarea name="rules"></textarea></label><label>Image<input type="file" name="image" accept="image/jpeg,image/png,image/webp"></label><label>Administrator<select name="admin_id"><option value="">Unassigned</option>@foreach($admins as $admin)<option value="{{ $admin->id }}">{{ $admin->name }}</option>@endforeach</select></label><button class="btn btn-primary">Create community</button></form></details></div>
        <div class="community-grid">
        @forelse($communities as $community)
            <article class="community-admin-card">
                <div class="community-card-main">@if($community->image)<img class="community-card-thumb" src="{{ $community->image }}" alt="">@else<div class="community-card-placeholder">{{ strtoupper(substr($community->name, 0, 1)) }}</div>@endif<div class="community-admin-head"><div><h3>{{ $community->name }}</h3><p>{{ $community->description ?: 'No description provided.' }}</p></div></div></div>
                <div class="community-meta"><span>Owner: {{ $community->admin?->name ?? 'Unassigned' }}</span><span>{{ $community->pending_applications_count }} pending</span></div>
                <div class="community-card-actions"><a class="manage-applications-link" href="{{ route('admin.communities.applications', $community) }}">Manage applications <span>{{ $community->pending_applications_count }}</span></a><span class="admin-pill">{{ number_format($community->members_count) }} members</span></div>
                <details><summary class="mini-btn">Edit details</summary>
                    <form class="admin-form compact" method="POST" action="{{ route('admin.communities.update', $community) }}" enctype="multipart/form-data">@csrf @method('PATCH')
                        <label>Name<input name="name" value="{{ $community->name }}" required></label>
                        <label>Description<textarea name="description">{{ $community->description }}</textarea></label>
                        <label>Rules<textarea name="rules">{{ $community->rules }}</textarea></label>
                        <label>Community image
                            @if($community->image)<img class="community-image-preview" src="{{ $community->image }}" alt="Current {{ $community->name }} image">@endif
                            <input name="image" type="file" accept="image/jpeg,image/png,image/webp"><small>JPG, PNG or WebP, up to 4 MB.</small>
                        </label>
                        <label>Administrator<select name="admin_id"><option value="">Unassigned</option>@foreach($admins as $admin)<option value="{{ $admin->id }}" @selected((int) $community->admin_id === (int) $admin->id)>{{ $admin->name }} · {{ $admin->role === 'super_admin' ? 'Super administrator' : 'Administrator' }}</option>@endforeach</select></label>
                        <button class="btn btn-primary" type="submit">Save changes</button>
                    </form>
                </details>
                <form method="POST" action="{{ route('admin.communities.destroy',$community) }}" onsubmit="return confirm('Delete this community and all of its posts, applications and quizzes?')">@csrf @method('DELETE')<button class="mini-btn danger">Delete community</button></form>
            </article>
        @empty<div class="empty-cell">No communities created yet.</div>@endforelse
        </div>
        @if($communities->hasPages())<nav class="admin-pagination" aria-label="Community pages">@if($communities->onFirstPage())<span>← Previous</span>@else<a href="{{ $communities->previousPageUrl() }}">← Previous</a>@endif<strong>Page {{ $communities->currentPage() }} of {{ $communities->lastPage() }}</strong>@if($communities->hasMorePages())<a href="{{ $communities->nextPageUrl() }}">Next →</a>@else<span>Next →</span>@endif</nav>@endif
    </section>
@elseif($section === 'posts')
    <div class="page-heading"><div><div class="eyebrow">Community moderation</div><h1>Community posts</h1><p>Review member posts before they become visible in their community.</p></div></div>
    <section class="stats post-stats">
        @foreach($postMetrics as $label => $value)<article class="card stat"><div class="stat-top"><span class="stat-icon {{ $label === 'Pending review' ? 'red' : '' }}"><svg class="icon">@if($label === 'Pending review')<path d="M12 8v5M12 17h.01M4 21h16L12 3z"/>@elseif($label === 'Approved')<path d="M5 12l4 4L19 6"/>@else<path d="M6 6l12 12M18 6 6 18"/>@endif</svg></span><span class="metric-live"><i></i> Live</span></div><div class="stat-value">{{ number_format($value) }}</div><div class="stat-label">{{ $label }}</div></article>@endforeach
    </section>
    <section class="card posts-panel"><div class="posts-toolbar"><div><h2>Post directory</h2><span><strong>{{ number_format($posts->total()) }}</strong> matching post{{ $posts->total()===1?'':'s' }}</span></div><form method="GET" action="{{ url('/admin/posts') }}" class="post-filter" data-post-filter><select name="status"><option value="">All statuses</option>@foreach(['pending','approved','rejected'] as $status)<option value="{{ $status }}" @selected($postStatus===$status)>{{ ucfirst($status) }}</option>@endforeach</select><select name="community"><option value="">All communities</option>@foreach($postCommunities as $community)<option value="{{ $community->id }}" @selected((string)$postCommunity===(string)$community->id)>{{ $community->name }}</option>@endforeach</select><button class="mini-btn">Apply filters</button>@if($postStatus || $postCommunity)<a class="clear-filter" href="{{ url('/admin/posts') }}">Clear</a>@endif</form></div>
        <div class="admin-table-wrap"><table class="admin-table"><thead><tr><th>Author</th><th>Community</th><th>Post</th><th>Status</th><th>Submitted</th><th>Actions</th></tr></thead><tbody>
        @forelse($posts as $post)<tr>
            <td><strong>{{ $post->user->name }}</strong><small>{{ $post->user->email }}</small></td>
            <td>{{ $post->community->name }}</td>
            <td style="max-width:420px"><a class="post-preview-link" href="{{ route('admin.posts.show',$post) }}">{{ Str::limit($post->content, 180) ?: 'View post details' }}</a></td>
            <td><span class="admin-pill {{ $post->status }}">{{ ucfirst($post->status) }}</span></td>
            <td>{{ $post->created_at->format('d M Y, H:i') }}</td>
            <td><div class="application-actions"><a class="mini-btn" href="{{ route('admin.posts.show',$post) }}">View details</a>@if($post->status === 'pending')<form method="POST" action="{{ route('admin.posts.review', $post) }}">@csrf<input type="hidden" name="action" value="approve"><button class="mini-btn approve">Approve</button></form><form method="POST" action="{{ route('admin.posts.review', $post) }}">@csrf<input type="hidden" name="action" value="reject"><button class="mini-btn danger">Reject</button></form>@endif</div></td>
        </tr>@empty<tr><td colspan="6"><div class="posts-empty"><span>▤</span><strong>No posts found</strong><small>Try changing the filters or check back when members submit new content.</small></div></td></tr>@endforelse
        </tbody></table></div>
        @if($posts->hasPages())<nav class="admin-pagination ajax-pagination" aria-label="Post pages">@if($posts->onFirstPage())<span>← Previous</span>@else<a href="{{ $posts->previousPageUrl() }}">← Previous</a>@endif<strong>Page {{ $posts->currentPage() }} of {{ $posts->lastPage() }}</strong>@if($posts->hasMorePages())<a href="{{ $posts->nextPageUrl() }}">Next →</a>@else<span>Next →</span>@endif</nav>@endif
    </section>
@elseif($section === 'quizzes')
    <nav class="learning-tabs"><a href="{{ url('/admin/articles') }}">Articles with quizzes</a><a class="active" href="{{ url('/admin/quizzes') }}">Standalone quizzes</a></nav>
    <div class="page-heading"><div><div class="eyebrow">Optional assessments</div><h1>Standalone quizzes</h1><p>Manage assessments that are not attached to a required reading article.</p></div><a class="btn btn-primary" href="{{ route('admin.quizzes.create') }}">+ Create standalone quiz</a></div>
    <section class="stats">@foreach($quizMetrics as $label=>$value)<article class="card stat"><div class="stat-value">{{ number_format($value) }}</div><div class="stat-label">{{ $label }}</div></article>@endforeach</section>
    <section class="card quiz-community-panel"><div class="panel-head"><div><h2>Communities available for quizzes</h2><div class="panel-sub">Every community below can have one or more quizzes.</div></div></div><div class="quiz-community-list">@forelse($quizCommunities as $community)<a href="{{ route('admin.quizzes.create',['community'=>$community->id]) }}"><span class="quiz-community-mark">{{ strtoupper(substr($community->name,0,1)) }}</span><span><strong>{{ $community->name }}</strong><small>{{ number_format($community->members_count) }} members</small></span><b>{{ $community->quizzes_count }} quiz{{ $community->quizzes_count===1?'':'zes' }}</b><i>＋</i></a>@empty<div class="empty-cell">Create a community before adding a quiz.</div>@endforelse</div></section>
    <section class="card quiz-library"><div class="panel-head"><div><h2>Quiz library</h2><div class="panel-sub">{{ number_format($quizzes->total()) }} quiz{{ $quizzes->total()===1?'':'zes' }} across all communities</div></div></div><div class="quiz-table-wrap"><table class="admin-table"><thead><tr><th>Quiz</th><th>Community</th><th>Questions</th><th>Passing score</th><th>Status</th><th>Updated</th><th></th></tr></thead><tbody>@forelse($quizzes as $quiz)<tr><td><strong>{{ $quiz->title }}</strong><small>{{ Str::limit($quiz->instructions ?: 'No instructions added.',70) }}</small></td><td>{{ $quiz->community->name }}</td><td>{{ $quiz->questions_count }}</td><td>{{ $quiz->passing_score }}%</td><td><span class="admin-pill {{ $quiz->status === 'published' ? 'approved' : 'pending' }}">{{ ucfirst($quiz->status) }}</span></td><td>{{ $quiz->updated_at->format('d M Y') }}</td><td><div class="quiz-row-actions"><a class="mini-btn" href="{{ route('admin.quizzes.edit',$quiz) }}">Edit quiz</a><form method="POST" action="{{ route('admin.quizzes.destroy',$quiz) }}" onsubmit="return confirm('Delete this quiz?')">@csrf @method('DELETE')<button class="mini-btn danger">Delete</button></form></div></td></tr>@empty<tr><td colspan="7" class="empty-cell">No quizzes yet. Choose a community above to create the first one.</td></tr>@endforelse</tbody></table></div>@if($quizzes->hasPages())<nav class="admin-pagination ajax-pagination">@if($quizzes->onFirstPage())<span>← Previous</span>@else<a href="{{ $quizzes->previousPageUrl() }}">← Previous</a>@endif<strong>Page {{ $quizzes->currentPage() }} of {{ $quizzes->lastPage() }}</strong>@if($quizzes->hasMorePages())<a href="{{ $quizzes->nextPageUrl() }}">Next →</a>@else<span>Next →</span>@endif</nav>@endif</section>
@elseif($section === 'articles')
    <nav class="learning-tabs"><a class="active" href="{{ url('/admin/articles') }}">Articles with quizzes</a><a href="{{ url('/admin/quizzes') }}">Standalone quizzes</a></nav>
    <div class="page-heading"><div><div class="eyebrow">Required learning</div><h1>Learning</h1><p>Create an article and its assessment together as one learning activity.</p></div><a class="btn btn-primary" href="{{ route('admin.articles.create') }}">+ Add learning activity</a></div>
    <section class="card quiz-community-panel"><div class="panel-head"><div><h2>Articles by community</h2><div class="panel-sub">Choose any community to add another article.</div></div></div><div class="quiz-community-list">@foreach($articleCommunities as $community)<a href="{{ route('admin.articles.create',['community'=>$community->id]) }}"><span class="quiz-community-mark">{{ strtoupper(substr($community->name,0,1)) }}</span><span><strong>{{ $community->name }}</strong><small>Learning content</small></span><b>{{ $community->learning_articles_count }} article{{ $community->learning_articles_count===1?'':'s' }}</b><i>＋</i></a>@endforeach</div></section>
    <section class="card quiz-library"><div class="panel-head"><div><h2>Article library</h2><div class="panel-sub">{{ $articles->total() }} article{{ $articles->total()===1?'':'s' }}</div></div></div><div class="quiz-table-wrap"><table class="admin-table"><thead><tr><th>Article</th><th>Community</th><th>Questions</th><th>Order</th><th>Status</th><th></th></tr></thead><tbody>@forelse($articles as $article)<tr><td><strong>{{ $article->title }}</strong><small>{{ Str::limit($article->content,90) }}</small></td><td>{{ $article->community->name }}</td><td>{{ $article->questions_count }}</td><td>{{ $article->position }}</td><td><span class="admin-pill {{ $article->status==='published'?'approved':'pending' }}">{{ ucfirst($article->status) }}</span></td><td><div class="quiz-row-actions"><a class="mini-btn" href="{{ route('admin.articles.edit',$article) }}">Edit article</a><form method="POST" action="{{ route('admin.articles.destroy',$article) }}" onsubmit="return confirm('Delete this article and its quiz?')">@csrf @method('DELETE')<button class="mini-btn danger">Delete</button></form></div></td></tr>@empty<tr><td colspan="6" class="empty-cell">No database articles yet. Add the first article for a community.</td></tr>@endforelse</tbody></table></div></section>
@elseif($section === 'moderation')
    <div class="page-heading"><div><div class="eyebrow">Safety & review</div><h1>Moderation</h1><p>Process applications, community posts and member support requests.</p></div></div>
    <section class="card panel"><h2>Pending applications</h2><div class="admin-table-wrap"><table class="admin-table"><tbody>@forelse($pendingApplications as $item)<tr><td><strong>{{ $item->user?->name }}</strong><small>{{ $item->community?->name }}</small></td><td><div class="application-actions"><form method="POST" action="{{ route('admin.applications.review',$item) }}">@csrf<input type="hidden" name="action" value="approve"><button class="mini-btn approve">Approve</button></form><form method="POST" action="{{ route('admin.applications.review',$item) }}">@csrf<input type="hidden" name="action" value="reject"><button class="mini-btn danger">Reject</button></form></div></td></tr>@empty<tr><td class="empty-cell">No pending applications.</td></tr>@endforelse</tbody></table></div>{{ $pendingApplications->links() }}</section>
    <section class="card panel"><h2>Pending posts</h2><div class="admin-table-wrap"><table class="admin-table"><tbody>@forelse($pendingPosts as $post)<tr><td><strong>{{ $post->user?->name }}</strong><small>{{ $post->community?->name }}</small></td><td>{{ Str::limit($post->content,160) }}</td><td><div class="application-actions"><form method="POST" action="{{ route('admin.posts.review',$post) }}">@csrf<input type="hidden" name="action" value="approve"><button class="mini-btn approve">Approve</button></form><form method="POST" action="{{ route('admin.posts.review',$post) }}">@csrf<input type="hidden" name="action" value="reject"><button class="mini-btn danger">Reject</button></form></div></td></tr>@empty<tr><td class="empty-cell">No pending posts.</td></tr>@endforelse</tbody></table></div>{{ $pendingPosts->links() }}</section>
    <section class="card panel"><h2>Support requests</h2><div class="admin-table-wrap"><table class="admin-table"><tbody>@forelse($supportRequests as $ticket)<tr><td><strong>#{{ $ticket->id }} {{ $ticket->subject }}</strong><small>{{ $ticket->user?->name }} · {{ $ticket->type }}</small></td><td>{{ $ticket->message }}</td><td><form method="POST" action="{{ route('admin.support.update',$ticket) }}">@csrf @method('PATCH')<select name="status">@foreach(['open','in_progress','resolved','closed'] as $status)<option value="{{ $status }}" @selected($ticket->status===$status)>{{ ucfirst(str_replace('_',' ',$status)) }}</option>@endforeach</select><button class="mini-btn">Save</button></form></td></tr>@empty<tr><td class="empty-cell">No support requests.</td></tr>@endforelse</tbody></table></div>{{ $supportRequests->links() }}</section>
@elseif($section === 'analytics')
    <div class="page-heading"><div><div class="eyebrow">Platform health</div><h1>Analytics</h1><p>Understand membership, publishing and community activity at a glance.</p></div><span class="analytics-updated">Updated {{ now()->format('d M Y, H:i') }}</span></div>
    <section class="stats analytics-stats">@foreach($analyticsMetrics as $label=>$value)<article class="card stat"><div class="stat-top"><span class="stat-icon"><svg class="icon"><path d="M4 20V10M10 20V4M16 20v-7M22 20H2"/></svg></span><span class="metric-live"><i></i> Live</span></div><div class="stat-value">{{ number_format($value) }}</div><div class="stat-label">{{ $label }}</div></article>@endforeach</section>
    @php
        $chartMax = max(1, $weeklyActivity->max(fn ($day) => max($day['members'], $day['posts'])));
    @endphp
    <section class="analytics-grid"><article class="card panel analytics-chart"><div class="panel-head"><div><h2>Activity this week</h2><div class="panel-sub">New members and posts over the last seven days</div></div><div class="chart-legend"><span><i class="members"></i>Members</span><span><i class="posts"></i>Posts</span></div></div><div class="activity-chart">@foreach($weeklyActivity as $day)<div class="chart-day"><div class="chart-values"><div class="chart-bar members" style="height:{{ max(5,($day['members']/$chartMax)*100) }}%" title="{{ $day['members'] }} members"></div><div class="chart-bar posts" style="height:{{ max(5,($day['posts']/$chartMax)*100) }}%" title="{{ $day['posts'] }} posts"></div></div><strong>{{ $day['label'] }}</strong><small>{{ $day['members'] + $day['posts'] }}</small></div>@endforeach</div></article><article class="card panel health-panel"><div class="panel-head"><div><h2>Platform health</h2><div class="panel-sub">Important operational indicators</div></div></div><div class="health-list">@foreach($analyticsRates as $label=>$value)<div><span>{{ $label }}</span><strong>{{ in_array($label,['Verification rate','Community content']) ? $value.'%' : number_format($value) }}</strong>@if(in_array($label,['Verification rate','Community content']))<i><b style="width:{{ $value }}%"></b></i>@endif</div>@endforeach</div></article></section>
    <section class="analytics-lower"><article class="card panel"><div class="panel-head"><div><h2>Community performance</h2><div class="panel-sub">Membership, publishing and application volume</div></div></div><div class="admin-table-wrap"><table class="admin-table"><thead><tr><th>Community</th><th>Members</th><th>Posts</th><th>Applications</th><th>Posts/member</th></tr></thead><tbody>@forelse($communityAnalytics as $community)<tr><td><strong>{{ $community->name }}</strong></td><td>{{ number_format($community->members_count) }}</td><td>{{ number_format($community->posts_count) }}</td><td>{{ number_format($community->applications_count) }}</td><td>{{ $community->members_count ? number_format($community->posts_count/$community->members_count,1) : '0.0' }}</td></tr>@empty<tr><td colspan="5" class="empty-cell">No community activity yet.</td></tr>@endforelse</tbody></table></div></article><article class="card panel"><div class="panel-head"><div><h2>Engagement</h2><div class="panel-sub">All-time interaction and learning totals</div></div></div><div class="engagement-list">@foreach($engagementTotals as $label=>$value)<div><span>{{ $label }}</span><strong>{{ number_format($value) }}</strong></div>@endforeach</div></article></section>
@elseif($section === 'settings')
    <div class="page-heading settings-heading"><div><div class="eyebrow">Platform configuration</div><h1>Settings</h1><p>Manage the public identity of LST Social and secure your administrator account.</p></div><span class="settings-saved"><i></i> Changes save immediately</span></div>
    <div class="settings-layout">
        <aside class="settings-nav card" role="tablist"><strong>Settings</strong><a class="active" href="#branding" data-settings-tab="branding" role="tab"><span>01</span><div>Brand & downloads<small>Public platform details</small></div></a><a href="#feed-banner" data-settings-tab="feed-banner" role="tab"><span>02</span><div>Feed banner<small>Encouragement or announcement</small></div></a><a href="#profile" data-settings-tab="profile" role="tab"><span>03</span><div>Administrator profile<small>Your name and email</small></div></a><a href="#security" data-settings-tab="security" role="tab"><span>04</span><div>Password & security<small>Protect your account</small></div></a></aside>
        <div class="settings-content">
            <section class="card settings-section" id="branding"><header class="settings-section-head"><span class="settings-icon"><svg class="icon"><path d="M4 20V8l8-5 8 5v12M8 20v-7h8v7"/></svg></span><div><h2>Brand & app downloads</h2><p>Details shown on the public landing page and download buttons.</p></div><span class="settings-public">Public</span></header><form class="admin-form settings-form" method="POST" action="{{ route('admin.settings.branding') }}">@csrf @method('PATCH')<div class="form-grid"><label>Organization name<input name="brand_name" value="{{ old('brand_name',$branding['brand_name']) }}" required><small>The organization behind the platform.</small></label><label>Product name<input name="product_name" value="{{ old('product_name',$branding['product_name']) }}" required><small>The app name displayed to members.</small></label></div><label>Public support email<input type="email" name="support_email" value="{{ old('support_email',$branding['support_email']) }}" required><small>Members will use this address when they need help.</small></label><div class="settings-divider"><span>Mobile app links</span></div><label>Apple App Store URL<input type="url" name="ios_app_url" value="{{ old('ios_app_url',$branding['ios_app_url']) }}" placeholder="https://apps.apple.com/app/..." required></label><label>Google Play URL<input type="url" name="android_app_url" value="{{ old('android_app_url',$branding['android_app_url']) }}" placeholder="https://play.google.com/store/apps/details?id=..." required></label><footer class="settings-form-actions"><span>These changes are visible to everyone.</span><button class="btn btn-primary">Save brand settings</button></footer></form></section>
            <section class="card settings-section" id="feed-banner"><header class="settings-section-head"><span class="settings-icon"><svg class="icon"><path d="M4 12h16M12 4v16"/></svg></span><div><h2>Home feed banner</h2><p>Choose exactly what members see above their feed.</p></div><span class="settings-public">In app</span></header><form class="admin-form settings-form" method="POST" action="{{ route('admin.settings.feed-banner') }}">@csrf @method('PATCH')<div class="settings-divider"><span>Banner to display</span></div><div class="form-grid"><label style="display:flex;flex-direction:row;align-items:center;gap:10px"><input type="radio" name="feed_banner_mode" value="encouragement" @checked(old('feed_banner_mode',$feedBanner['mode']) === 'encouragement') style="width:auto"><span>Daily encouragement</span></label><label style="display:flex;flex-direction:row;align-items:center;gap:10px"><input type="radio" name="feed_banner_mode" value="announcement" @checked(old('feed_banner_mode',$feedBanner['mode']) === 'announcement') style="width:auto"><span>Admin announcement</span></label></div><label>Announcement title<input name="announcement_title" maxlength="80" value="{{ old('announcement_title',$feedBanner['announcement_title']) }}" placeholder="Important update"><small>Up to 80 characters.</small></label><label>Short announcement<textarea name="announcement_text" maxlength="240" rows="4" placeholder="Tell members what they need to know…">{{ old('announcement_text',$feedBanner['announcement_text']) }}</textarea><small>Required when Admin announcement is selected; up to 240 characters.</small></label><label>Continue link (optional)<input type="url" name="announcement_action_url" value="{{ old('announcement_action_url',$feedBanner['announcement_action_url']) }}" placeholder="https://example.com/details"><small>When provided, members see “Click here to continue”. HTTPS links only.</small></label><footer class="settings-form-actions"><span>Your selected mode appears in the app after refresh.</span><button class="btn btn-primary">Save feed banner</button></footer></form></section>
            <section class="settings-account-grid"><article class="card settings-section" id="profile"><header class="settings-section-head"><span class="settings-icon"><svg class="icon"><circle cx="12" cy="8" r="4"/><path d="M5 21c1-5 3.5-7 7-7s6 2 7 7"/></svg></span><div><h2>Administrator profile</h2><p>Update your personal account information.</p></div></header><form class="admin-form settings-form" method="POST" action="{{ route('admin.settings.profile') }}">@csrf @method('PATCH')<label>Full name<input name="name" value="{{ old('name',$admin->name) }}" required></label><label>Email address<input type="email" name="email" value="{{ old('email',$admin->email) }}" required></label><footer class="settings-form-actions"><span>Signed in as {{ ucfirst(str_replace('_',' ',$admin->role)) }}</span><button class="btn btn-primary">Save profile</button></footer></form></article><article class="card settings-section" id="security"><header class="settings-section-head"><span class="settings-icon security"><svg class="icon"><rect x="5" y="10" width="14" height="11" rx="2"/><path d="M8 10V7a4 4 0 0 1 8 0v3M12 14v3"/></svg></span><div><h2>Password & security</h2><p>Use at least eight characters for your password.</p></div></header><form class="admin-form settings-form" method="POST" action="{{ route('admin.settings.password') }}">@csrf @method('PATCH')<label>Current password<input type="password" name="current_password" autocomplete="current-password" required></label><label>New password<input type="password" name="password" minlength="8" autocomplete="new-password" required></label><label>Confirm new password<input type="password" name="password_confirmation" minlength="8" autocomplete="new-password" required></label><footer class="settings-form-actions"><span>Your password is stored securely.</span><button class="btn btn-primary">Update password</button></footer></form></article></section>
        </div>
    </div>
@else
    @php
        $content = [
            'overview' => ['Overview', 'Monitor your entire LST Social workspace.'], 'posts' => ['Posts', 'Review and manage community posts.'], 'quizzes' => ['Quizzes', 'Control questions and pass requirements.'], 'moderation' => ['Moderation', 'Review reports and safety actions.'], 'analytics' => ['Analytics', 'Understand growth and engagement.'], 'settings' => ['Settings', 'Configure platform access and security.'],
        ];
        [$title, $description] = $content[$section];
    @endphp
    <div class="page-heading"><div><div class="eyebrow">Admin workspace</div><h1>{{ $title }}</h1><p>{{ $description }}</p></div></div>
    <section class="card panel"><div class="empty-cell">This section is ready for its next management workflow.</div></section>
@endif
