@php($existingQuestions = $quiz?->questions ?? collect())
<label>Community<select name="community_id" required><option value="">Choose community</option>@foreach($quizCommunities as $community)<option value="{{ $community->id }}" @selected((int)old('community_id',$quiz?->community_id)===(int)$community->id)>{{ $community->name }}</option>@endforeach</select></label>
<label>Title<input name="title" value="{{ old('title',$quiz?->title) }}" required></label>
<label>Instructions<textarea name="instructions">{{ old('instructions',$quiz?->instructions) }}</textarea></label>
<div class="form-grid"><label>Duration (minutes)<input type="number" min="1" max="600" name="duration_minutes" value="{{ old('duration_minutes',$quiz?->duration_minutes) }}"></label><label>Passing score %<input type="number" min="1" max="100" name="passing_score" value="{{ old('passing_score',$quiz?->passing_score ?? 80) }}" required></label><label>Maximum attempts<input type="number" min="1" max="100" name="max_attempts" value="{{ old('max_attempts',$quiz?->max_attempts) }}"></label><label>Status<select name="status"><option value="draft" @selected(old('status',$quiz?->status)==='draft')>Draft</option><option value="published" @selected(old('status',$quiz?->status ?? 'published')==='published')>Published</option></select></label></div>
<label><input type="checkbox" name="randomize_questions" value="1" @checked(old('randomize_questions',$quiz?->randomize_questions))> Randomize questions</label><label><input type="checkbox" name="show_answers" value="1" @checked(old('show_answers',$quiz?->show_answers ?? true))> Show answers after completion</label>
<div data-question-list>
@forelse($existingQuestions as $questionIndex=>$question)
    <fieldset class="quiz-question"><legend>Question <span data-question-number>{{ $questionIndex+1 }}</span></legend><label>Question<input name="questions[{{ $questionIndex }}][question]" value="{{ $question->question }}" required></label><div class="form-grid">@foreach($question->answers as $answerIndex=>$answer)<label>Answer {{ $answerIndex+1 }}<input name="questions[{{ $questionIndex }}][answers][{{ $answerIndex }}]" value="{{ $answer->answer }}" required></label>@endforeach</div><label>Correct answer<select name="questions[{{ $questionIndex }}][correct]">@foreach($question->answers as $answerIndex=>$answer)<option value="{{ $answerIndex }}" @selected($answer->is_correct)>Answer {{ $answerIndex+1 }}</option>@endforeach</select></label><button class="mini-btn danger" type="button" data-remove-question>Remove question</button></fieldset>
@empty
    <fieldset class="quiz-question"><legend>Question <span data-question-number>1</span></legend><label>Question<input name="questions[0][question]" required></label><div class="form-grid"><label>Answer 1<input name="questions[0][answers][0]" required></label><label>Answer 2<input name="questions[0][answers][1]" required></label><label>Answer 3<input name="questions[0][answers][2]" required></label><label>Answer 4<input name="questions[0][answers][3]" required></label></div><label>Correct answer<select name="questions[0][correct]"><option value="0">Answer 1</option><option value="1">Answer 2</option><option value="2">Answer 3</option><option value="3">Answer 4</option></select></label><button class="mini-btn danger" type="button" data-remove-question>Remove question</button></fieldset>
@endforelse
</div>
<button class="mini-btn" type="button" data-add-question>Add question</button>
<button class="btn btn-primary" type="submit">{{ $quiz ? 'Save quiz' : 'Create quiz' }}</button>
