<div data-report-history-content data-current-url="{{ $reports->url($reports->currentPage()) }}">
    <div class="panel-head"><div><h2>Report history</h2><div class="panel-sub">{{ number_format($reports->total()) }} report{{ $reports->total() === 1 ? '' : 's' }} across posts, profiles and private messages.</div></div></div>
    <form class="report-toolbar" data-report-filter action="{{ route('admin.reports.history') }}">
        <input name="search" value="{{ $reportSearch }}" placeholder="Search member or report details" aria-label="Search reports">
        <select name="type" aria-label="Filter by report type"><option value="">All content types</option>@foreach(['post','user','message'] as $type)<option value="{{ $type }}" @selected($reportType === $type)>{{ ucfirst($type) }}</option>@endforeach</select>
        <select name="status" aria-label="Filter by status"><option value="">All statuses</option>@foreach(['pending','reviewed','actioned','dismissed'] as $status)<option value="{{ $status }}" @selected($reportStatus === $status)>{{ ucfirst($status) }}</option>@endforeach</select>
        <button class="mini-btn" type="submit">Apply</button>
        @if($reportSearch || $reportType || $reportStatus)<a class="mini-btn" data-report-clear href="{{ route('admin.reports.history') }}">Clear</a>@endif
    </form>
    <div class="admin-table-wrap"><table class="admin-table report-table"><thead><tr><th>Report</th><th>Reported content</th><th>Reason</th><th>Review status</th></tr></thead><tbody>@forelse($reports as $report)<tr><td><strong>{{ ucfirst($report->target_type) }} #{{ $report->target_id }}</strong><small>Reported by {{ $report->reporter?->name ?? 'Deleted member' }} · {{ $report->created_at->diffForHumans() }}</small>@if($report->reportedUser)<small>Account: {{ $report->reportedUser->name }} · {{ $report->reportedUser->email }}</small>@endif</td><td><span class="report-excerpt">{{ Str::limit($report->content_excerpt,180) }}</span>@if($report->details)<small><b>Member note:</b> {{ $report->details }}</small>@endif</td><td><span class="admin-pill">{{ ucfirst(str_replace('_',' ',$report->reason)) }}</span></td><td><form class="report-status-form" data-report-action method="POST" action="{{ route('admin.reports.update',$report) }}">@csrf @method('PATCH')<select name="status">@foreach(['pending','reviewed','actioned','dismissed'] as $status)<option value="{{ $status }}" @selected($report->status===$status)>{{ ucfirst($status) }}</option>@endforeach</select><button class="mini-btn">Save</button></form>@if($report->reviewer)<small>By {{ $report->reviewer->name }} · {{ $report->reviewed_at?->diffForHumans() }}</small>@endif</td></tr>@empty<tr><td colspan="4" class="empty-cell">No reports match these filters.</td></tr>@endforelse</tbody></table></div>
    @if($reports->hasPages())<nav class="admin-pagination report-pagination" aria-label="Report history pages"><span>Showing {{ $reports->firstItem() }}–{{ $reports->lastItem() }} of {{ $reports->total() }}</span><div>@if($reports->onFirstPage())<span>Previous</span>@else<a data-report-page href="{{ $reports->previousPageUrl() }}">Previous</a>@endif @foreach(range(max(1,$reports->currentPage()-2),min($reports->lastPage(),$reports->currentPage()+2)) as $page)<a data-report-page class="{{ $page === $reports->currentPage() ? 'active' : '' }}" href="{{ $reports->url($page) }}" @if($page === $reports->currentPage()) aria-current="page" @endif>{{ $page }}</a>@endforeach @if($reports->hasMorePages())<a data-report-page href="{{ $reports->nextPageUrl() }}">Next</a>@else<span>Next</span>@endif</div></nav>@elseif($reports->total())<div class="report-total">Showing all {{ $reports->total() }} reports</div>@endif
</div>
