<?php

use App\Http\Controllers\Api\AuthController;
use App\Http\Controllers\Api\ConnectionController;
use App\Http\Controllers\Api\SocialController;
use App\Http\Controllers\Api\PushTokenController;
use App\Models\Comment;
use Illuminate\Support\Facades\Route;

Route::middleware('throttle:6,1')->group(function () {
    Route::post('/register', [AuthController::class, 'register']);
    Route::post('/register/check-email', [AuthController::class, 'checkEmail']);
    Route::post('/login', [AuthController::class, 'login']);
    Route::post('/forgot-password/otp', [AuthController::class, 'sendForgotPasswordOtp']);
    Route::post('/forgot-password/reset', [AuthController::class, 'resetForgottenPassword']);
});

Route::middleware('auth:sanctum')->group(function () {
    Route::post('/logout', [AuthController::class, 'logout']);
    Route::get('/user', [AuthController::class, 'me']);
    Route::post('/email/verification-notification', [AuthController::class, 'sendVerification'])->middleware('throttle:3,1');
    Route::post('/email/verify-otp', [AuthController::class, 'verifyEmailOtp'])->middleware('throttle:6,1');
    Route::delete('/user', [AuthController::class, 'destroy'])->middleware('throttle:3,1');
    Route::post('/user/password/otp', [AuthController::class, 'sendChangePasswordOtp'])->middleware('throttle:3,1');
    Route::patch('/user/password', [AuthController::class, 'changePassword'])->middleware('throttle:6,1');
    Route::patch('/user', [SocialController::class, 'updateProfile'])->middleware('throttle:media-uploads');
    Route::get('/users/search', [ConnectionController::class, 'searchUsers']);
    Route::get('/friend-requests', [ConnectionController::class, 'friendRequests']);
    Route::get('/blocked-users', [ConnectionController::class, 'blockedUsers']);
    Route::get('/birthday-celebrations', [ConnectionController::class, 'birthdayCelebrations']);
    Route::post('/users/{user}/birthday-wish', [ConnectionController::class, 'wishBirthday'])->middleware('throttle:message-sends');
    Route::get('/users/{user}', [SocialController::class, 'user']);
    Route::get('/users/{user}/posts', [SocialController::class, 'userPosts']);
    Route::get('/posts', [SocialController::class, 'posts']);
    Route::get('/feed-banner', [SocialController::class, 'feedBanner']);
    Route::get('/sermons', [SocialController::class, 'sermons']);
    Route::get('/sermons/{sermon}', [SocialController::class, 'sermon']);
    Route::post('/sermons/{sermon}/like', [SocialController::class, 'likeSermon'])->middleware('throttle:social-interactions');
    Route::get('/sermons/{sermon}/comments', [SocialController::class, 'sermonComments']);
    Route::post('/sermons/{sermon}/comments', [SocialController::class, 'createSermonComment'])->middleware('throttle:social-interactions');
    Route::get('/sermons/{sermon}/comments/{sermonComment}/replies', [SocialController::class, 'sermonCommentReplies']);
    Route::post('/sermon-comments/{sermonComment}/like', [SocialController::class, 'likeSermonComment'])->middleware('throttle:social-interactions');
    Route::patch('/sermon-comments/{sermonComment}', [SocialController::class, 'updateSermonComment'])->middleware('throttle:social-writes');
    Route::delete('/sermon-comments/{sermonComment}', [SocialController::class, 'deleteSermonComment'])->middleware('throttle:social-writes');
    Route::post('/reports', [SocialController::class, 'reportContent'])->middleware('throttle:10,1');
    Route::post('/posts', [SocialController::class, 'createPost'])->middleware('throttle:media-uploads');
    Route::patch('/posts/{post}', [SocialController::class, 'updatePost'])->middleware('throttle:media-uploads');
    Route::delete('/posts/{post}', [SocialController::class, 'deletePost'])->middleware('throttle:social-writes');
    Route::get('/posts/{post}', [SocialController::class, 'post']);
    Route::post('/posts/{post}/like', [SocialController::class, 'like'])->middleware('throttle:social-interactions');
    Route::post('/posts/{post}/share', [SocialController::class, 'sharePost'])->middleware('throttle:social-writes');
    Route::post('/posts/{post}/comments', [SocialController::class, 'comment'])->middleware('throttle:social-interactions');
    Route::get('/posts/{post}/comments', [SocialController::class, 'comments']);
    Route::get('/posts/{post}/comments/{comment}/replies', [SocialController::class, 'replies']);
    Route::post('/comments/{comment}/like', [SocialController::class, 'likeComment'])->middleware('throttle:social-interactions');
    Route::patch('/comments/{comment}', [SocialController::class, 'updateComment'])->middleware('throttle:social-writes');
    Route::delete('/comments/{comment}', [SocialController::class, 'deleteComment'])->middleware('throttle:social-writes');
    Route::get('/saved-posts', [SocialController::class, 'saved']);
    Route::post('/posts/{post}/save', [SocialController::class, 'toggleSaved'])->middleware('throttle:social-interactions');
    Route::get('/communities', [SocialController::class, 'communities']);
    Route::get('/communities/{community}', [SocialController::class, 'community']);
    Route::get('/communities/{community}/articles', [SocialController::class, 'communityArticles']);
    Route::get('/communities/{community}/posts', [SocialController::class, 'communityPosts']);
    Route::get('/communities/{community}/members', [SocialController::class, 'members']);
    Route::get('/communities/{community}/member-directory', [SocialController::class, 'memberDirectory']);
    Route::post('/communities/{community}/join', [SocialController::class, 'join'])->middleware('throttle:relationship-writes');
    Route::delete('/communities/{community}/leave', [SocialController::class, 'leave'])->middleware('throttle:relationship-writes');
    Route::post('/communities/{community}/posts', [SocialController::class, 'createCommunityPost'])->middleware('throttle:media-uploads');
    Route::get('/community-applications', [SocialController::class, 'applications']);
    Route::post('/communities/{community}/applications', [SocialController::class, 'apply'])->middleware('throttle:relationship-writes');
    Route::delete('/communities/{community}/applications', [SocialController::class, 'withdraw'])->middleware('throttle:relationship-writes');
    Route::get('/communities/{community}/moderation', [SocialController::class, 'moderationQueue']);
    Route::post('/communities/{community}/moderation/applications/{application}', [SocialController::class, 'reviewCommunityApplication'])->middleware('throttle:social-writes');
    Route::post('/communities/{community}/moderation/posts/{post}', [SocialController::class, 'reviewCommunityPost'])->middleware('throttle:social-writes');
    Route::get('/friendships', [ConnectionController::class, 'friendships']);
    Route::get('/friends', [ConnectionController::class, 'friends']);
    Route::post('/users/{user}/friend-request', [ConnectionController::class, 'request'])->middleware('throttle:relationship-writes');
    Route::post('/users/{user}/relationship', [ConnectionController::class, 'act'])->middleware('throttle:relationship-writes');
    Route::get('/chats', [ConnectionController::class, 'chats']);
    Route::get('/chats-unread-count', [ConnectionController::class, 'unreadChatCount']);
    Route::post('/chats/with/{user}', [ConnectionController::class, 'createChat'])->middleware('throttle:relationship-writes');
    Route::get('/chats/{chat}', [ConnectionController::class, 'chat']);
    Route::get('/chats/{chat}/messages', [ConnectionController::class, 'messages']);
    Route::post('/chats/{chat}/messages', [ConnectionController::class, 'send'])->middleware('throttle:message-sends');
    Route::patch('/chats/{chat}/messages/{message}', [ConnectionController::class, 'updateMessage'])->middleware('throttle:social-writes');
    Route::delete('/chats/{chat}/messages/{message}', [ConnectionController::class, 'deleteMessage'])->middleware('throttle:social-writes');
    Route::post('/chats/{chat}/messages/{message}/reaction', [ConnectionController::class, 'reactToMessage'])->middleware('throttle:social-writes');
    Route::get('/notifications', [SocialController::class, 'notifications']);
    Route::post('/notifications/read-all', [SocialController::class, 'readAll']);
    Route::post('/notifications/{notification}/read', [SocialController::class, 'readNotification']);
    Route::post('/push-tokens', [PushTokenController::class, 'store'])->middleware('throttle:10,1');
    Route::delete('/push-tokens', [PushTokenController::class, 'destroy'])->middleware('throttle:10,1');
    Route::post('/support-requests', [SocialController::class, 'submitSupportRequest'])->middleware('throttle:10,1');
});
