export const mockPosts = [
          {
            id: '1',
            userId: 'u1',
            userName: 'Grace Johnson',
            userAvatar: 'https://i.pravatar.cc/100?img=1',
            content: '"Trust in the Lord with all your heart…" – Proverbs 3:5. This verse has carried me through tough times. Share your favourite verse below! 🙏',
            image: 'https://picsum.photos/400/200?random=1',
            likes: 24,
            comments: [
              { id: 'c1', userId: 'u2', userName: 'David', text: 'Amen! That’s my anchor verse.', timestamp: '2h ago' },
              { id: 'c2', userId: 'u3', userName: 'Sarah', text: 'I love that one too. ❤️', timestamp: '1h ago' },
            ],
            timestamp: '3h ago',
            communityId: null,
            type: 'Encouragement',
            audience: 'Everyone',
            verified: false,
          },
          {
            id: '2',
            userId: 'u4',
            userName: 'Pastor Michael',
            userAvatar: 'https://i.pravatar.cc/100?img=4',
            content: 'Join our community "Sexual Puritans and Virgins" – a safe space to pursue purity together. Rules: single and committed to abstinence. Click to join!',
            image: null,
            likes: 42,
            comments: [],
            timestamp: '5h ago',
            communityId: 'comm1',
            type: 'Community',
            audience: 'Purity circle',
            verified: true,
          },
          {
            id: '3',
            userId: 'u3',
            userName: 'Sarah Williams',
            userAvatar: 'https://i.pravatar.cc/100?img=3',
            content: 'Please keep my family in your prayers this week. We are walking through a difficult season, but I am choosing to trust God one day at a time. Pray especially for wisdom, peace in our home, and strength to keep showing up for one another. I am grateful to have a community where we can carry one another without judgment.',
            image: null,
            likes: 31,
            comments: [
              { id: 'c3', userId: 'u2', userName: 'David', text: 'Standing with your family in prayer. May peace fill your home.', timestamp: '45m ago' },
            ],
            timestamp: '1h ago',
            communityId: null,
            type: 'Prayer',
            audience: 'Everyone',
            verified: false,
          },
          {
            id: '4',
            userId: 'u5',
            userName: 'Daniel Okafor',
            userAvatar: 'https://i.pravatar.cc/100?img=11',
            content: 'A year ago I was afraid to tell anyone that I was struggling. I thought faith meant always appearing strong. Recovery has taught me something different: honesty is not the enemy of faith; it is often where healing begins. Today marks nine months of sobriety. I am thankful for every person who checked in, prayed without preaching at me, and reminded me that one difficult day does not erase the progress already made.',
            image: 'https://picsum.photos/600/420?random=21',
            likes: 86,
            comments: [
              { id: 'c4', userId: 'u1', userName: 'Grace Johnson', text: 'Your courage will help someone else choose honesty today. Proud of you.', timestamp: '2h ago' },
              { id: 'c5', userId: 'u6', userName: 'James Cole', text: 'One day at a time. Congratulations on nine months!', timestamp: '1h ago' },
            ],
            timestamp: '4h ago',
            communityId: 'comm2',
            type: 'Testimony',
            audience: 'Recovery circle',
            verified: false,
          },
          {
            id: '5',
            userId: 'u7',
            userName: 'Ruth Mensah',
            userAvatar: 'https://i.pravatar.cc/100?img=32',
            content: 'Marriage restoration is rarely one dramatic moment. For us it has been a hundred small decisions: listening before defending, apologising without adding an excuse, praying when conversation becomes difficult, and choosing not to keep a record of old wounds. We are still learning, but our home feels hopeful again. If you are in a hard season, please do not mistake slow progress for no progress.',
            image: null,
            likes: 64,
            comments: [
              { id: 'c6', userId: 'u8', userName: 'Mary Adeyemi', text: 'I needed the reminder that slow progress still counts.', timestamp: '3h ago' },
            ],
            timestamp: '6h ago',
            communityId: 'comm3',
            type: 'Testimony',
            audience: 'Marriage healing',
            verified: true,
          },
          {
            id: '6',
            userId: 'u9',
            userName: 'David Eze',
            userAvatar: 'https://i.pravatar.cc/100?img=12',
            content: 'What does healthy Christian courtship look like when both people have demanding careers and serve actively in church? We are trying to create rhythms that leave room for honest conversations, wise counsel, rest, and friendship—not only wedding planning. I would appreciate practical lessons from couples who have walked through this season well.',
            image: null,
            likes: 19,
            comments: [
              { id: 'c7', userId: 'u4', userName: 'Pastor Michael', text: 'Protect time for friendship and do not make every conversation about decisions.', timestamp: '2h ago' },
              { id: 'c8', userId: 'u1', userName: 'Grace Johnson', text: 'A shared weekly check-in helped us talk about expectations early.', timestamp: '1h ago' },
            ],
            timestamp: '8h ago',
            communityId: 'comm5',
            type: 'Community',
            audience: 'Courtship circle',
            verified: false,
          },
          {
            id: '7',
            userId: 'u10',
            userName: 'Mary Adeyemi',
            userAvatar: 'https://i.pravatar.cc/100?img=25',
            content: 'This morning I wrote down three things I am grateful for before looking at my phone: breath, another chance to begin, and the people who make ordinary days feel meaningful. Gratitude did not remove the work waiting for me, but it changed the spirit in which I approached it. What is one ordinary gift you are grateful for today?',
            image: 'https://picsum.photos/600/420?random=22',
            likes: 47,
            comments: [],
            timestamp: '10h ago',
            communityId: null,
            type: 'Encouragement',
            audience: 'Everyone',
            verified: false,
          },
          {
            id: '8',
            userId: 'u11',
            userName: 'James Cole',
            userAvatar: 'https://i.pravatar.cc/100?img=14',
            content: 'Please pray for everyone quietly rebuilding after a setback. Some victories are public, but much of healing happens where nobody applauds: attending another counselling session, deleting a number, returning to a support meeting, admitting the truth to a trusted friend, or simply getting through tonight without returning to an old habit. May God give each person courage for the next right step.',
            image: null,
            likes: 73,
            comments: [
              { id: 'c9', userId: 'u3', userName: 'Sarah Williams', text: 'Amen. Praying especially for the people doing the unseen work.', timestamp: '4h ago' },
            ],
            timestamp: '12h ago',
            communityId: 'comm2',
            type: 'Prayer',
            audience: 'Recovery circle',
            verified: false,
          },
          {
            id: '9',
            userId: 'u12',
            userName: 'Esther Bello',
            userAvatar: 'https://i.pravatar.cc/100?img=47',
            content: 'Singleness is not a waiting room where life remains paused until marriage arrives. This season can hold deep friendships, meaningful service, financial wisdom, healing, travel, study, laughter, and a closer walk with God. Desire for marriage is valid, but it does not make today incomplete. I am learning to prepare for the future without refusing the gifts already present.',
            image: 'https://picsum.photos/600/420?random=23',
            likes: 101,
            comments: [
              { id: 'c10', userId: 'u5', userName: 'Daniel Okafor', text: '“Prepare without refusing today” is such a good way to put it.', timestamp: '5h ago' },
              { id: 'c11', userId: 'u7', userName: 'Ruth Mensah', text: 'A full life is not postponed. Thank you for sharing this.', timestamp: '4h ago' },
            ],
            timestamp: '1d ago',
            communityId: 'comm7',
            type: 'Encouragement',
            audience: 'Whole singles',
            verified: false,
          },
          {
            id: '10',
            userId: 'u4',
            userName: 'Pastor Michael',
            userAvatar: 'https://i.pravatar.cc/100?img=4',
            content: 'A gentle reminder for this week: community is not only a place to receive support. It is also an invitation to notice who has become quiet, celebrate another person without comparison, make room for a new voice, and offer help before being asked. Healthy fellowship grows when every member takes responsibility for the atmosphere we create together.',
            image: null,
            likes: 58,
            comments: [],
            timestamp: '1d ago',
            communityId: null,
            type: 'Encouragement',
            audience: 'Everyone',
            verified: true,
          },
        ];

        export const mockCommunities = [
          {
            id: 'comm1',
            name: 'Sexual Puritans & Virgins',
            description: 'For singles pursuing purity and holiness.',
            rules: 'Must be single and committed to abstinence.',
            memberCount: 128,
            image: 'https://picsum.photos/200/200?random=10',
            admin: 'Pastor Michael',
            memberIds: ['u4', 'u2', 'u3', 'u9'],
            posts: [
              { id: 'p1', content: 'Weekly purity challenge: spend 30 minutes in prayer daily.', timestamp: '1d ago' },
            ],
          },
          {
            id: 'comm2',
            name: 'Addiction Recovery',
            description: 'Support for those overcoming addictions.',
            rules: 'Active in recovery and sober ≥30 days.',
            memberCount: 93,
            image: 'https://picsum.photos/200/200?random=11',
            admin: 'Brother James',
            memberIds: ['u5', 'u11', 'u2'],
            posts: [
              { id: 'p2', content: 'Celebrate your milestones! Share your testimony.', timestamp: '2d ago' },
            ],
          },
          {
            id: 'comm3',
            name: 'Maritally Challenged (Healing)',
            description: 'Restoration for marriages in crisis.',
            rules: 'Married and seeking healing.',
            memberCount: 76,
            image: 'https://picsum.photos/200/200?random=12',
            admin: 'Sister Ruth',
            memberIds: ['u7', 'u10', 'u3'],
            posts: [],
          },
          {
            id: 'comm4',
            name: 'Quick Marital Settlement',
            description: 'Engaged or planning to marry within 6 months.',
            rules: 'Engaged or with a clear wedding date.',
            memberCount: 45,
            image: 'https://picsum.photos/200/200?random=13',
            admin: 'Elder Peter',
            memberIds: ['u4', 'u9'],
            posts: [],
          },
          {
            id: 'comm5',
            name: 'Couples in Courtship',
            description: 'Mentorship for courting couples.',
            rules: 'In courtship and need mentorship.',
            memberCount: 62,
            image: 'https://picsum.photos/200/200?random=14',
            admin: 'Pastor David',
            memberIds: ['u9', 'u3', 'u10'],
            posts: [],
          },
          {
            id: 'comm6',
            name: 'Special Disciples',
            description: 'Invitation-only leadership group.',
            rules: 'Invitation-only / leadership approval.',
            memberCount: 18,
            image: 'https://picsum.photos/200/200?random=15',
            admin: 'Apostle John',
            memberIds: ['u4', 'u11'],
            posts: [],
          },
          {
            id: 'comm7',
            name: 'All-Round Whole Singles',
            description: 'Single and on a mission for God.',
            rules: 'Single and actively serving.',
            memberCount: 210,
            image: 'https://picsum.photos/200/200?random=16',
            admin: 'Sister Mary',
            memberIds: ['u12', 'u3', 'u9'],
            posts: [],
          },
        ];

        export const mockChats = [
          {
            id: 'chat1',
            withUser: { id: 'u2', name: 'David', avatar: 'https://i.pravatar.cc/100?img=2' },
            lastMessage: 'See you at the prayer meeting!',
            timestamp: '12:30 PM',
          },
          {
            id: 'chat2',
            withUser: { id: 'u3', name: 'Sarah', avatar: 'https://i.pravatar.cc/100?img=3' },
            lastMessage: 'Could you pray for my family?',
            timestamp: 'Yesterday',
          },
        ];

        export const mockMessages = {
          chat1: [
            { id: 'm1', senderId: 'u1', text: 'Hey David, how are you?', timestamp: '11:00 AM' },
            { id: 'm2', senderId: 'u2', text: 'I’m blessed! How about you?', timestamp: '11:05 AM' },
            { id: 'm3', senderId: 'u1', text: 'See you at the prayer meeting!', timestamp: '12:30 PM' },
          ],
          chat2: [
            { id: 'm4', senderId: 'u3', text: 'Could you pray for my family?', timestamp: 'Yesterday' },
            { id: 'm5', senderId: 'u1', text: 'Of course, I will.', timestamp: 'Yesterday' },
          ],
        };

        export const mockUser = {
          id: 'u1',
          name: 'Grace Johnson',
          email: 'grace@example.com',
          avatar: 'https://i.pravatar.cc/200?img=1',
          bio: 'Lover of Jesus. Wife. Mom. Worship leader.',
          joinedCommunities: ['comm1', 'comm7'],
        };

        export const mockUsers = [
          mockUser,
          { id: 'u2', name: 'David Eze', email: 'david@example.com', avatar: 'https://i.pravatar.cc/200?img=2', bio: 'Growing in grace. Prayer team volunteer.', joinedCommunities: ['comm1', 'comm2'] },
          { id: 'u3', name: 'Sarah Williams', email: 'sarah@example.com', avatar: 'https://i.pravatar.cc/200?img=3', bio: 'Wife, sister, and lover of honest community.', joinedCommunities: ['comm1', 'comm3', 'comm5'] },
          { id: 'u4', name: 'Pastor Michael', email: 'michael@example.com', avatar: 'https://i.pravatar.cc/200?img=4', bio: 'Pastor and mentor helping people grow with wisdom.', joinedCommunities: ['comm1', 'comm4', 'comm6'], role: 'Community leader' },
          { id: 'u5', name: 'Daniel Okafor', email: 'daniel@example.com', avatar: 'https://i.pravatar.cc/200?img=11', bio: 'Recovery advocate. One day at a time.', joinedCommunities: ['comm2'] },
          { id: 'u7', name: 'Ruth Mensah', email: 'ruth@example.com', avatar: 'https://i.pravatar.cc/200?img=32', bio: 'Marriage mentor and family-life facilitator.', joinedCommunities: ['comm3'], role: 'Community leader' },
          { id: 'u9', name: 'David Eze', email: 'davideze@example.com', avatar: 'https://i.pravatar.cc/200?img=12', bio: 'Serving, learning, and preparing for marriage.', joinedCommunities: ['comm1', 'comm4', 'comm5'] },
          { id: 'u10', name: 'Mary Adeyemi', email: 'mary@example.com', avatar: 'https://i.pravatar.cc/200?img=25', bio: 'Grateful for ordinary grace and meaningful friendships.', joinedCommunities: ['comm3', 'comm5'] },
          { id: 'u11', name: 'James Cole', email: 'james@example.com', avatar: 'https://i.pravatar.cc/200?img=14', bio: 'Helping others find courage for the next right step.', joinedCommunities: ['comm2', 'comm6'] },
          { id: 'u12', name: 'Esther Bello', email: 'esther@example.com', avatar: 'https://i.pravatar.cc/200?img=47', bio: 'Living a full life of faith, purpose, and service.', joinedCommunities: ['comm7'] },
        ];
      
